/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodosRouteImport } from './routes/todos'
import { Route as TableRouteImport } from './routes/table'
import { Route as StoreRouteImport } from './routes/store'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as FormsRouteImport } from './routes/forms'
import { Route as DatabaseRouteImport } from './routes/database'
import { Route as TenantRouteImport } from './routes/$tenant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FormsSimpleRouteImport } from './routes/forms.simple'
import { Route as FormsAddressRouteImport } from './routes/forms.address'
import { Route as AuthSignUpRouteImport } from './routes/auth.sign-up'
import { Route as ApiTodosRouteImport } from './routes/api.todos'
import { Route as TenantAppRouteImport } from './routes/$tenant.app'
import { Route as ApiUserOrganizationsRouteImport } from './routes/api.user.organizations'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as TenantAppSupportRouteImport } from './routes/$tenant.app.support'
import { Route as TenantAppSalesRouteImport } from './routes/$tenant.app.sales'
import { Route as TenantAppLoginRouteImport } from './routes/$tenant.app.login'
import { Route as TenantAppSupportIndexRouteImport } from './routes/$tenant.app.support.index'
import { Route as TenantAppSalesIndexRouteImport } from './routes/$tenant.app.sales.index'
import { Route as ApiTenantTenantUsersRouteImport } from './routes/api.tenant.$tenant.users'
import { Route as ApiTenantTenantTicketsRouteImport } from './routes/api.tenant.$tenant.tickets'
import { Route as ApiTenantTenantMembershipRouteImport } from './routes/api.tenant.$tenant.membership'
import { Route as TenantAppSupportTicketsRouteImport } from './routes/$tenant.app.support.tickets'
import { Route as TenantAppSupportMembersRouteImport } from './routes/$tenant.app.support.members'
import { Route as TenantAppSupportKnowledgeRouteImport } from './routes/$tenant.app.support.knowledge'
import { Route as TenantAppSalesSubscriptionsRouteImport } from './routes/$tenant.app.sales.subscriptions'
import { Route as TenantAppSalesProductCatalogRouteImport } from './routes/$tenant.app.sales.product-catalog'
import { Route as TenantAppSalesPipelineRouteImport } from './routes/$tenant.app.sales.pipeline'
import { Route as TenantAppSalesCrmRouteImport } from './routes/$tenant.app.sales.crm'
import { Route as ApiTenantTenantTicketsTicketIdRouteImport } from './routes/api.tenant.$tenant.tickets.$ticketId'
import { Route as ApiTenantTenantKnowledgeSearchRouteImport } from './routes/api.tenant.$tenant.knowledge.search'
import { Route as ApiTenantTenantKnowledgePlaybooksRouteImport } from './routes/api.tenant.$tenant.knowledge.playbooks'
import { Route as ApiTenantTenantKnowledgeArticlesRouteImport } from './routes/api.tenant.$tenant.knowledge.articles'

const TodosRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const TableRoute = TableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsRoute = FormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => rootRouteImport,
} as any)
const DatabaseRoute = DatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantRoute = TenantRouteImport.update({
  id: '/$tenant',
  path: '/$tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsSimpleRoute = FormsSimpleRouteImport.update({
  id: '/simple',
  path: '/simple',
  getParentRoute: () => FormsRoute,
} as any)
const FormsAddressRoute = FormsAddressRouteImport.update({
  id: '/address',
  path: '/address',
  getParentRoute: () => FormsRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTodosRoute = ApiTodosRouteImport.update({
  id: '/api/todos',
  path: '/api/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantAppRoute = TenantAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => TenantRoute,
} as any)
const ApiUserOrganizationsRoute = ApiUserOrganizationsRouteImport.update({
  id: '/api/user/organizations',
  path: '/api/user/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantAppSupportRoute = TenantAppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => TenantAppRoute,
} as any)
const TenantAppSalesRoute = TenantAppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => TenantAppRoute,
} as any)
const TenantAppLoginRoute = TenantAppLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => TenantAppRoute,
} as any)
const TenantAppSupportIndexRoute = TenantAppSupportIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TenantAppSupportRoute,
} as any)
const TenantAppSalesIndexRoute = TenantAppSalesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TenantAppSalesRoute,
} as any)
const ApiTenantTenantUsersRoute = ApiTenantTenantUsersRouteImport.update({
  id: '/api/tenant/$tenant/users',
  path: '/api/tenant/$tenant/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTenantTenantTicketsRoute = ApiTenantTenantTicketsRouteImport.update({
  id: '/api/tenant/$tenant/tickets',
  path: '/api/tenant/$tenant/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTenantTenantMembershipRoute =
  ApiTenantTenantMembershipRouteImport.update({
    id: '/api/tenant/$tenant/membership',
    path: '/api/tenant/$tenant/membership',
    getParentRoute: () => rootRouteImport,
  } as any)
const TenantAppSupportTicketsRoute = TenantAppSupportTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => TenantAppSupportRoute,
} as any)
const TenantAppSupportMembersRoute = TenantAppSupportMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => TenantAppSupportRoute,
} as any)
const TenantAppSupportKnowledgeRoute =
  TenantAppSupportKnowledgeRouteImport.update({
    id: '/knowledge',
    path: '/knowledge',
    getParentRoute: () => TenantAppSupportRoute,
  } as any)
const TenantAppSalesSubscriptionsRoute =
  TenantAppSalesSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => TenantAppSalesRoute,
  } as any)
const TenantAppSalesProductCatalogRoute =
  TenantAppSalesProductCatalogRouteImport.update({
    id: '/product-catalog',
    path: '/product-catalog',
    getParentRoute: () => TenantAppSalesRoute,
  } as any)
const TenantAppSalesPipelineRoute = TenantAppSalesPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => TenantAppSalesRoute,
} as any)
const TenantAppSalesCrmRoute = TenantAppSalesCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => TenantAppSalesRoute,
} as any)
const ApiTenantTenantTicketsTicketIdRoute =
  ApiTenantTenantTicketsTicketIdRouteImport.update({
    id: '/$ticketId',
    path: '/$ticketId',
    getParentRoute: () => ApiTenantTenantTicketsRoute,
  } as any)
const ApiTenantTenantKnowledgeSearchRoute =
  ApiTenantTenantKnowledgeSearchRouteImport.update({
    id: '/api/tenant/$tenant/knowledge/search',
    path: '/api/tenant/$tenant/knowledge/search',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTenantTenantKnowledgePlaybooksRoute =
  ApiTenantTenantKnowledgePlaybooksRouteImport.update({
    id: '/api/tenant/$tenant/knowledge/playbooks',
    path: '/api/tenant/$tenant/knowledge/playbooks',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTenantTenantKnowledgeArticlesRoute =
  ApiTenantTenantKnowledgeArticlesRouteImport.update({
    id: '/api/tenant/$tenant/knowledge/articles',
    path: '/api/tenant/$tenant/knowledge/articles',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$tenant': typeof TenantRouteWithChildren
  '/database': typeof DatabaseRoute
  '/forms': typeof FormsRouteWithChildren
  '/mcp': typeof McpRoute
  '/store': typeof StoreRoute
  '/table': typeof TableRoute
  '/todos': typeof TodosRoute
  '/$tenant/app': typeof TenantAppRouteWithChildren
  '/api/todos': typeof ApiTodosRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/forms/address': typeof FormsAddressRoute
  '/forms/simple': typeof FormsSimpleRoute
  '/$tenant/app/login': typeof TenantAppLoginRoute
  '/$tenant/app/sales': typeof TenantAppSalesRouteWithChildren
  '/$tenant/app/support': typeof TenantAppSupportRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/user/organizations': typeof ApiUserOrganizationsRoute
  '/$tenant/app/sales/crm': typeof TenantAppSalesCrmRoute
  '/$tenant/app/sales/pipeline': typeof TenantAppSalesPipelineRoute
  '/$tenant/app/sales/product-catalog': typeof TenantAppSalesProductCatalogRoute
  '/$tenant/app/sales/subscriptions': typeof TenantAppSalesSubscriptionsRoute
  '/$tenant/app/support/knowledge': typeof TenantAppSupportKnowledgeRoute
  '/$tenant/app/support/members': typeof TenantAppSupportMembersRoute
  '/$tenant/app/support/tickets': typeof TenantAppSupportTicketsRoute
  '/api/tenant/$tenant/membership': typeof ApiTenantTenantMembershipRoute
  '/api/tenant/$tenant/tickets': typeof ApiTenantTenantTicketsRouteWithChildren
  '/api/tenant/$tenant/users': typeof ApiTenantTenantUsersRoute
  '/$tenant/app/sales/': typeof TenantAppSalesIndexRoute
  '/$tenant/app/support/': typeof TenantAppSupportIndexRoute
  '/api/tenant/$tenant/knowledge/articles': typeof ApiTenantTenantKnowledgeArticlesRoute
  '/api/tenant/$tenant/knowledge/playbooks': typeof ApiTenantTenantKnowledgePlaybooksRoute
  '/api/tenant/$tenant/knowledge/search': typeof ApiTenantTenantKnowledgeSearchRoute
  '/api/tenant/$tenant/tickets/$ticketId': typeof ApiTenantTenantTicketsTicketIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$tenant': typeof TenantRouteWithChildren
  '/database': typeof DatabaseRoute
  '/forms': typeof FormsRouteWithChildren
  '/mcp': typeof McpRoute
  '/store': typeof StoreRoute
  '/table': typeof TableRoute
  '/todos': typeof TodosRoute
  '/$tenant/app': typeof TenantAppRouteWithChildren
  '/api/todos': typeof ApiTodosRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/forms/address': typeof FormsAddressRoute
  '/forms/simple': typeof FormsSimpleRoute
  '/$tenant/app/login': typeof TenantAppLoginRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/user/organizations': typeof ApiUserOrganizationsRoute
  '/$tenant/app/sales/crm': typeof TenantAppSalesCrmRoute
  '/$tenant/app/sales/pipeline': typeof TenantAppSalesPipelineRoute
  '/$tenant/app/sales/product-catalog': typeof TenantAppSalesProductCatalogRoute
  '/$tenant/app/sales/subscriptions': typeof TenantAppSalesSubscriptionsRoute
  '/$tenant/app/support/knowledge': typeof TenantAppSupportKnowledgeRoute
  '/$tenant/app/support/members': typeof TenantAppSupportMembersRoute
  '/$tenant/app/support/tickets': typeof TenantAppSupportTicketsRoute
  '/api/tenant/$tenant/membership': typeof ApiTenantTenantMembershipRoute
  '/api/tenant/$tenant/tickets': typeof ApiTenantTenantTicketsRouteWithChildren
  '/api/tenant/$tenant/users': typeof ApiTenantTenantUsersRoute
  '/$tenant/app/sales': typeof TenantAppSalesIndexRoute
  '/$tenant/app/support': typeof TenantAppSupportIndexRoute
  '/api/tenant/$tenant/knowledge/articles': typeof ApiTenantTenantKnowledgeArticlesRoute
  '/api/tenant/$tenant/knowledge/playbooks': typeof ApiTenantTenantKnowledgePlaybooksRoute
  '/api/tenant/$tenant/knowledge/search': typeof ApiTenantTenantKnowledgeSearchRoute
  '/api/tenant/$tenant/tickets/$ticketId': typeof ApiTenantTenantTicketsTicketIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$tenant': typeof TenantRouteWithChildren
  '/database': typeof DatabaseRoute
  '/forms': typeof FormsRouteWithChildren
  '/mcp': typeof McpRoute
  '/store': typeof StoreRoute
  '/table': typeof TableRoute
  '/todos': typeof TodosRoute
  '/$tenant/app': typeof TenantAppRouteWithChildren
  '/api/todos': typeof ApiTodosRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/forms/address': typeof FormsAddressRoute
  '/forms/simple': typeof FormsSimpleRoute
  '/$tenant/app/login': typeof TenantAppLoginRoute
  '/$tenant/app/sales': typeof TenantAppSalesRouteWithChildren
  '/$tenant/app/support': typeof TenantAppSupportRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/user/organizations': typeof ApiUserOrganizationsRoute
  '/$tenant/app/sales/crm': typeof TenantAppSalesCrmRoute
  '/$tenant/app/sales/pipeline': typeof TenantAppSalesPipelineRoute
  '/$tenant/app/sales/product-catalog': typeof TenantAppSalesProductCatalogRoute
  '/$tenant/app/sales/subscriptions': typeof TenantAppSalesSubscriptionsRoute
  '/$tenant/app/support/knowledge': typeof TenantAppSupportKnowledgeRoute
  '/$tenant/app/support/members': typeof TenantAppSupportMembersRoute
  '/$tenant/app/support/tickets': typeof TenantAppSupportTicketsRoute
  '/api/tenant/$tenant/membership': typeof ApiTenantTenantMembershipRoute
  '/api/tenant/$tenant/tickets': typeof ApiTenantTenantTicketsRouteWithChildren
  '/api/tenant/$tenant/users': typeof ApiTenantTenantUsersRoute
  '/$tenant/app/sales/': typeof TenantAppSalesIndexRoute
  '/$tenant/app/support/': typeof TenantAppSupportIndexRoute
  '/api/tenant/$tenant/knowledge/articles': typeof ApiTenantTenantKnowledgeArticlesRoute
  '/api/tenant/$tenant/knowledge/playbooks': typeof ApiTenantTenantKnowledgePlaybooksRoute
  '/api/tenant/$tenant/knowledge/search': typeof ApiTenantTenantKnowledgeSearchRoute
  '/api/tenant/$tenant/tickets/$ticketId': typeof ApiTenantTenantTicketsTicketIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$tenant'
    | '/database'
    | '/forms'
    | '/mcp'
    | '/store'
    | '/table'
    | '/todos'
    | '/$tenant/app'
    | '/api/todos'
    | '/auth/sign-up'
    | '/forms/address'
    | '/forms/simple'
    | '/$tenant/app/login'
    | '/$tenant/app/sales'
    | '/$tenant/app/support'
    | '/api/auth/$'
    | '/api/user/organizations'
    | '/$tenant/app/sales/crm'
    | '/$tenant/app/sales/pipeline'
    | '/$tenant/app/sales/product-catalog'
    | '/$tenant/app/sales/subscriptions'
    | '/$tenant/app/support/knowledge'
    | '/$tenant/app/support/members'
    | '/$tenant/app/support/tickets'
    | '/api/tenant/$tenant/membership'
    | '/api/tenant/$tenant/tickets'
    | '/api/tenant/$tenant/users'
    | '/$tenant/app/sales/'
    | '/$tenant/app/support/'
    | '/api/tenant/$tenant/knowledge/articles'
    | '/api/tenant/$tenant/knowledge/playbooks'
    | '/api/tenant/$tenant/knowledge/search'
    | '/api/tenant/$tenant/tickets/$ticketId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$tenant'
    | '/database'
    | '/forms'
    | '/mcp'
    | '/store'
    | '/table'
    | '/todos'
    | '/$tenant/app'
    | '/api/todos'
    | '/auth/sign-up'
    | '/forms/address'
    | '/forms/simple'
    | '/$tenant/app/login'
    | '/api/auth/$'
    | '/api/user/organizations'
    | '/$tenant/app/sales/crm'
    | '/$tenant/app/sales/pipeline'
    | '/$tenant/app/sales/product-catalog'
    | '/$tenant/app/sales/subscriptions'
    | '/$tenant/app/support/knowledge'
    | '/$tenant/app/support/members'
    | '/$tenant/app/support/tickets'
    | '/api/tenant/$tenant/membership'
    | '/api/tenant/$tenant/tickets'
    | '/api/tenant/$tenant/users'
    | '/$tenant/app/sales'
    | '/$tenant/app/support'
    | '/api/tenant/$tenant/knowledge/articles'
    | '/api/tenant/$tenant/knowledge/playbooks'
    | '/api/tenant/$tenant/knowledge/search'
    | '/api/tenant/$tenant/tickets/$ticketId'
  id:
    | '__root__'
    | '/'
    | '/$tenant'
    | '/database'
    | '/forms'
    | '/mcp'
    | '/store'
    | '/table'
    | '/todos'
    | '/$tenant/app'
    | '/api/todos'
    | '/auth/sign-up'
    | '/forms/address'
    | '/forms/simple'
    | '/$tenant/app/login'
    | '/$tenant/app/sales'
    | '/$tenant/app/support'
    | '/api/auth/$'
    | '/api/user/organizations'
    | '/$tenant/app/sales/crm'
    | '/$tenant/app/sales/pipeline'
    | '/$tenant/app/sales/product-catalog'
    | '/$tenant/app/sales/subscriptions'
    | '/$tenant/app/support/knowledge'
    | '/$tenant/app/support/members'
    | '/$tenant/app/support/tickets'
    | '/api/tenant/$tenant/membership'
    | '/api/tenant/$tenant/tickets'
    | '/api/tenant/$tenant/users'
    | '/$tenant/app/sales/'
    | '/$tenant/app/support/'
    | '/api/tenant/$tenant/knowledge/articles'
    | '/api/tenant/$tenant/knowledge/playbooks'
    | '/api/tenant/$tenant/knowledge/search'
    | '/api/tenant/$tenant/tickets/$ticketId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TenantRoute: typeof TenantRouteWithChildren
  DatabaseRoute: typeof DatabaseRoute
  FormsRoute: typeof FormsRouteWithChildren
  McpRoute: typeof McpRoute
  StoreRoute: typeof StoreRoute
  TableRoute: typeof TableRoute
  TodosRoute: typeof TodosRoute
  ApiTodosRoute: typeof ApiTodosRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiUserOrganizationsRoute: typeof ApiUserOrganizationsRoute
  ApiTenantTenantMembershipRoute: typeof ApiTenantTenantMembershipRoute
  ApiTenantTenantTicketsRoute: typeof ApiTenantTenantTicketsRouteWithChildren
  ApiTenantTenantUsersRoute: typeof ApiTenantTenantUsersRoute
  ApiTenantTenantKnowledgeArticlesRoute: typeof ApiTenantTenantKnowledgeArticlesRoute
  ApiTenantTenantKnowledgePlaybooksRoute: typeof ApiTenantTenantKnowledgePlaybooksRoute
  ApiTenantTenantKnowledgeSearchRoute: typeof ApiTenantTenantKnowledgeSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table': {
      id: '/table'
      path: '/table'
      fullPath: '/table'
      preLoaderRoute: typeof TableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms': {
      id: '/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof FormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/database': {
      id: '/database'
      path: '/database'
      fullPath: '/database'
      preLoaderRoute: typeof DatabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tenant': {
      id: '/$tenant'
      path: '/$tenant'
      fullPath: '/$tenant'
      preLoaderRoute: typeof TenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/simple': {
      id: '/forms/simple'
      path: '/simple'
      fullPath: '/forms/simple'
      preLoaderRoute: typeof FormsSimpleRouteImport
      parentRoute: typeof FormsRoute
    }
    '/forms/address': {
      id: '/forms/address'
      path: '/address'
      fullPath: '/forms/address'
      preLoaderRoute: typeof FormsAddressRouteImport
      parentRoute: typeof FormsRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/todos': {
      id: '/api/todos'
      path: '/api/todos'
      fullPath: '/api/todos'
      preLoaderRoute: typeof ApiTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tenant/app': {
      id: '/$tenant/app'
      path: '/app'
      fullPath: '/$tenant/app'
      preLoaderRoute: typeof TenantAppRouteImport
      parentRoute: typeof TenantRoute
    }
    '/api/user/organizations': {
      id: '/api/user/organizations'
      path: '/api/user/organizations'
      fullPath: '/api/user/organizations'
      preLoaderRoute: typeof ApiUserOrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tenant/app/support': {
      id: '/$tenant/app/support'
      path: '/support'
      fullPath: '/$tenant/app/support'
      preLoaderRoute: typeof TenantAppSupportRouteImport
      parentRoute: typeof TenantAppRoute
    }
    '/$tenant/app/sales': {
      id: '/$tenant/app/sales'
      path: '/sales'
      fullPath: '/$tenant/app/sales'
      preLoaderRoute: typeof TenantAppSalesRouteImport
      parentRoute: typeof TenantAppRoute
    }
    '/$tenant/app/login': {
      id: '/$tenant/app/login'
      path: '/login'
      fullPath: '/$tenant/app/login'
      preLoaderRoute: typeof TenantAppLoginRouteImport
      parentRoute: typeof TenantAppRoute
    }
    '/$tenant/app/support/': {
      id: '/$tenant/app/support/'
      path: '/'
      fullPath: '/$tenant/app/support/'
      preLoaderRoute: typeof TenantAppSupportIndexRouteImport
      parentRoute: typeof TenantAppSupportRoute
    }
    '/$tenant/app/sales/': {
      id: '/$tenant/app/sales/'
      path: '/'
      fullPath: '/$tenant/app/sales/'
      preLoaderRoute: typeof TenantAppSalesIndexRouteImport
      parentRoute: typeof TenantAppSalesRoute
    }
    '/api/tenant/$tenant/users': {
      id: '/api/tenant/$tenant/users'
      path: '/api/tenant/$tenant/users'
      fullPath: '/api/tenant/$tenant/users'
      preLoaderRoute: typeof ApiTenantTenantUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tenant/$tenant/tickets': {
      id: '/api/tenant/$tenant/tickets'
      path: '/api/tenant/$tenant/tickets'
      fullPath: '/api/tenant/$tenant/tickets'
      preLoaderRoute: typeof ApiTenantTenantTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tenant/$tenant/membership': {
      id: '/api/tenant/$tenant/membership'
      path: '/api/tenant/$tenant/membership'
      fullPath: '/api/tenant/$tenant/membership'
      preLoaderRoute: typeof ApiTenantTenantMembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tenant/app/support/tickets': {
      id: '/$tenant/app/support/tickets'
      path: '/tickets'
      fullPath: '/$tenant/app/support/tickets'
      preLoaderRoute: typeof TenantAppSupportTicketsRouteImport
      parentRoute: typeof TenantAppSupportRoute
    }
    '/$tenant/app/support/members': {
      id: '/$tenant/app/support/members'
      path: '/members'
      fullPath: '/$tenant/app/support/members'
      preLoaderRoute: typeof TenantAppSupportMembersRouteImport
      parentRoute: typeof TenantAppSupportRoute
    }
    '/$tenant/app/support/knowledge': {
      id: '/$tenant/app/support/knowledge'
      path: '/knowledge'
      fullPath: '/$tenant/app/support/knowledge'
      preLoaderRoute: typeof TenantAppSupportKnowledgeRouteImport
      parentRoute: typeof TenantAppSupportRoute
    }
    '/$tenant/app/sales/subscriptions': {
      id: '/$tenant/app/sales/subscriptions'
      path: '/subscriptions'
      fullPath: '/$tenant/app/sales/subscriptions'
      preLoaderRoute: typeof TenantAppSalesSubscriptionsRouteImport
      parentRoute: typeof TenantAppSalesRoute
    }
    '/$tenant/app/sales/product-catalog': {
      id: '/$tenant/app/sales/product-catalog'
      path: '/product-catalog'
      fullPath: '/$tenant/app/sales/product-catalog'
      preLoaderRoute: typeof TenantAppSalesProductCatalogRouteImport
      parentRoute: typeof TenantAppSalesRoute
    }
    '/$tenant/app/sales/pipeline': {
      id: '/$tenant/app/sales/pipeline'
      path: '/pipeline'
      fullPath: '/$tenant/app/sales/pipeline'
      preLoaderRoute: typeof TenantAppSalesPipelineRouteImport
      parentRoute: typeof TenantAppSalesRoute
    }
    '/$tenant/app/sales/crm': {
      id: '/$tenant/app/sales/crm'
      path: '/crm'
      fullPath: '/$tenant/app/sales/crm'
      preLoaderRoute: typeof TenantAppSalesCrmRouteImport
      parentRoute: typeof TenantAppSalesRoute
    }
    '/api/tenant/$tenant/tickets/$ticketId': {
      id: '/api/tenant/$tenant/tickets/$ticketId'
      path: '/$ticketId'
      fullPath: '/api/tenant/$tenant/tickets/$ticketId'
      preLoaderRoute: typeof ApiTenantTenantTicketsTicketIdRouteImport
      parentRoute: typeof ApiTenantTenantTicketsRoute
    }
    '/api/tenant/$tenant/knowledge/search': {
      id: '/api/tenant/$tenant/knowledge/search'
      path: '/api/tenant/$tenant/knowledge/search'
      fullPath: '/api/tenant/$tenant/knowledge/search'
      preLoaderRoute: typeof ApiTenantTenantKnowledgeSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tenant/$tenant/knowledge/playbooks': {
      id: '/api/tenant/$tenant/knowledge/playbooks'
      path: '/api/tenant/$tenant/knowledge/playbooks'
      fullPath: '/api/tenant/$tenant/knowledge/playbooks'
      preLoaderRoute: typeof ApiTenantTenantKnowledgePlaybooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tenant/$tenant/knowledge/articles': {
      id: '/api/tenant/$tenant/knowledge/articles'
      path: '/api/tenant/$tenant/knowledge/articles'
      fullPath: '/api/tenant/$tenant/knowledge/articles'
      preLoaderRoute: typeof ApiTenantTenantKnowledgeArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TenantAppSalesRouteChildren {
  TenantAppSalesCrmRoute: typeof TenantAppSalesCrmRoute
  TenantAppSalesPipelineRoute: typeof TenantAppSalesPipelineRoute
  TenantAppSalesProductCatalogRoute: typeof TenantAppSalesProductCatalogRoute
  TenantAppSalesSubscriptionsRoute: typeof TenantAppSalesSubscriptionsRoute
  TenantAppSalesIndexRoute: typeof TenantAppSalesIndexRoute
}

const TenantAppSalesRouteChildren: TenantAppSalesRouteChildren = {
  TenantAppSalesCrmRoute: TenantAppSalesCrmRoute,
  TenantAppSalesPipelineRoute: TenantAppSalesPipelineRoute,
  TenantAppSalesProductCatalogRoute: TenantAppSalesProductCatalogRoute,
  TenantAppSalesSubscriptionsRoute: TenantAppSalesSubscriptionsRoute,
  TenantAppSalesIndexRoute: TenantAppSalesIndexRoute,
}

const TenantAppSalesRouteWithChildren = TenantAppSalesRoute._addFileChildren(
  TenantAppSalesRouteChildren,
)

interface TenantAppSupportRouteChildren {
  TenantAppSupportKnowledgeRoute: typeof TenantAppSupportKnowledgeRoute
  TenantAppSupportMembersRoute: typeof TenantAppSupportMembersRoute
  TenantAppSupportTicketsRoute: typeof TenantAppSupportTicketsRoute
  TenantAppSupportIndexRoute: typeof TenantAppSupportIndexRoute
}

const TenantAppSupportRouteChildren: TenantAppSupportRouteChildren = {
  TenantAppSupportKnowledgeRoute: TenantAppSupportKnowledgeRoute,
  TenantAppSupportMembersRoute: TenantAppSupportMembersRoute,
  TenantAppSupportTicketsRoute: TenantAppSupportTicketsRoute,
  TenantAppSupportIndexRoute: TenantAppSupportIndexRoute,
}

const TenantAppSupportRouteWithChildren =
  TenantAppSupportRoute._addFileChildren(TenantAppSupportRouteChildren)

interface TenantAppRouteChildren {
  TenantAppLoginRoute: typeof TenantAppLoginRoute
  TenantAppSalesRoute: typeof TenantAppSalesRouteWithChildren
  TenantAppSupportRoute: typeof TenantAppSupportRouteWithChildren
}

const TenantAppRouteChildren: TenantAppRouteChildren = {
  TenantAppLoginRoute: TenantAppLoginRoute,
  TenantAppSalesRoute: TenantAppSalesRouteWithChildren,
  TenantAppSupportRoute: TenantAppSupportRouteWithChildren,
}

const TenantAppRouteWithChildren = TenantAppRoute._addFileChildren(
  TenantAppRouteChildren,
)

interface TenantRouteChildren {
  TenantAppRoute: typeof TenantAppRouteWithChildren
}

const TenantRouteChildren: TenantRouteChildren = {
  TenantAppRoute: TenantAppRouteWithChildren,
}

const TenantRouteWithChildren =
  TenantRoute._addFileChildren(TenantRouteChildren)

interface FormsRouteChildren {
  FormsAddressRoute: typeof FormsAddressRoute
  FormsSimpleRoute: typeof FormsSimpleRoute
}

const FormsRouteChildren: FormsRouteChildren = {
  FormsAddressRoute: FormsAddressRoute,
  FormsSimpleRoute: FormsSimpleRoute,
}

const FormsRouteWithChildren = FormsRoute._addFileChildren(FormsRouteChildren)

interface ApiTenantTenantTicketsRouteChildren {
  ApiTenantTenantTicketsTicketIdRoute: typeof ApiTenantTenantTicketsTicketIdRoute
}

const ApiTenantTenantTicketsRouteChildren: ApiTenantTenantTicketsRouteChildren =
  {
    ApiTenantTenantTicketsTicketIdRoute: ApiTenantTenantTicketsTicketIdRoute,
  }

const ApiTenantTenantTicketsRouteWithChildren =
  ApiTenantTenantTicketsRoute._addFileChildren(
    ApiTenantTenantTicketsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TenantRoute: TenantRouteWithChildren,
  DatabaseRoute: DatabaseRoute,
  FormsRoute: FormsRouteWithChildren,
  McpRoute: McpRoute,
  StoreRoute: StoreRoute,
  TableRoute: TableRoute,
  TodosRoute: TodosRoute,
  ApiTodosRoute: ApiTodosRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiUserOrganizationsRoute: ApiUserOrganizationsRoute,
  ApiTenantTenantMembershipRoute: ApiTenantTenantMembershipRoute,
  ApiTenantTenantTicketsRoute: ApiTenantTenantTicketsRouteWithChildren,
  ApiTenantTenantUsersRoute: ApiTenantTenantUsersRoute,
  ApiTenantTenantKnowledgeArticlesRoute: ApiTenantTenantKnowledgeArticlesRoute,
  ApiTenantTenantKnowledgePlaybooksRoute:
    ApiTenantTenantKnowledgePlaybooksRoute,
  ApiTenantTenantKnowledgeSearchRoute: ApiTenantTenantKnowledgeSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
