/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodosRouteImport } from './routes/todos'
import { Route as TableRouteImport } from './routes/table'
import { Route as StoreRouteImport } from './routes/store'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as FormsRouteImport } from './routes/forms'
import { Route as DatabaseRouteImport } from './routes/database'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FormsSimpleRouteImport } from './routes/forms.simple'
import { Route as FormsAddressRouteImport } from './routes/forms.address'
import { Route as AppSupportRouteImport } from './routes/app.support'
import { Route as ApiTodosRouteImport } from './routes/api.todos'
import { Route as AppSupportIndexRouteImport } from './routes/app.support.index'
import { Route as AppSupportTicketsRouteImport } from './routes/app.support.tickets'

const TodosRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const TableRoute = TableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsRoute = FormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => rootRouteImport,
} as any)
const DatabaseRoute = DatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsSimpleRoute = FormsSimpleRouteImport.update({
  id: '/simple',
  path: '/simple',
  getParentRoute: () => FormsRoute,
} as any)
const FormsAddressRoute = FormsAddressRouteImport.update({
  id: '/address',
  path: '/address',
  getParentRoute: () => FormsRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRoute,
} as any)
const ApiTodosRoute = ApiTodosRouteImport.update({
  id: '/api/todos',
  path: '/api/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSupportIndexRoute = AppSupportIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSupportRoute,
} as any)
const AppSupportTicketsRoute = AppSupportTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AppSupportRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/database': typeof DatabaseRoute
  '/forms': typeof FormsRouteWithChildren
  '/mcp': typeof McpRoute
  '/store': typeof StoreRoute
  '/table': typeof TableRoute
  '/todos': typeof TodosRoute
  '/api/todos': typeof ApiTodosRoute
  '/app/support': typeof AppSupportRouteWithChildren
  '/forms/address': typeof FormsAddressRoute
  '/forms/simple': typeof FormsSimpleRoute
  '/app/support/tickets': typeof AppSupportTicketsRoute
  '/app/support/': typeof AppSupportIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/database': typeof DatabaseRoute
  '/forms': typeof FormsRouteWithChildren
  '/mcp': typeof McpRoute
  '/store': typeof StoreRoute
  '/table': typeof TableRoute
  '/todos': typeof TodosRoute
  '/api/todos': typeof ApiTodosRoute
  '/forms/address': typeof FormsAddressRoute
  '/forms/simple': typeof FormsSimpleRoute
  '/app/support/tickets': typeof AppSupportTicketsRoute
  '/app/support': typeof AppSupportIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/database': typeof DatabaseRoute
  '/forms': typeof FormsRouteWithChildren
  '/mcp': typeof McpRoute
  '/store': typeof StoreRoute
  '/table': typeof TableRoute
  '/todos': typeof TodosRoute
  '/api/todos': typeof ApiTodosRoute
  '/app/support': typeof AppSupportRouteWithChildren
  '/forms/address': typeof FormsAddressRoute
  '/forms/simple': typeof FormsSimpleRoute
  '/app/support/tickets': typeof AppSupportTicketsRoute
  '/app/support/': typeof AppSupportIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/database'
    | '/forms'
    | '/mcp'
    | '/store'
    | '/table'
    | '/todos'
    | '/api/todos'
    | '/app/support'
    | '/forms/address'
    | '/forms/simple'
    | '/app/support/tickets'
    | '/app/support/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/database'
    | '/forms'
    | '/mcp'
    | '/store'
    | '/table'
    | '/todos'
    | '/api/todos'
    | '/forms/address'
    | '/forms/simple'
    | '/app/support/tickets'
    | '/app/support'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/database'
    | '/forms'
    | '/mcp'
    | '/store'
    | '/table'
    | '/todos'
    | '/api/todos'
    | '/app/support'
    | '/forms/address'
    | '/forms/simple'
    | '/app/support/tickets'
    | '/app/support/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DatabaseRoute: typeof DatabaseRoute
  FormsRoute: typeof FormsRouteWithChildren
  McpRoute: typeof McpRoute
  StoreRoute: typeof StoreRoute
  TableRoute: typeof TableRoute
  TodosRoute: typeof TodosRoute
  ApiTodosRoute: typeof ApiTodosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table': {
      id: '/table'
      path: '/table'
      fullPath: '/table'
      preLoaderRoute: typeof TableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms': {
      id: '/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof FormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/database': {
      id: '/database'
      path: '/database'
      fullPath: '/database'
      preLoaderRoute: typeof DatabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/simple': {
      id: '/forms/simple'
      path: '/simple'
      fullPath: '/forms/simple'
      preLoaderRoute: typeof FormsSimpleRouteImport
      parentRoute: typeof FormsRoute
    }
    '/forms/address': {
      id: '/forms/address'
      path: '/address'
      fullPath: '/forms/address'
      preLoaderRoute: typeof FormsAddressRouteImport
      parentRoute: typeof FormsRoute
    }
    '/app/support': {
      id: '/app/support'
      path: '/support'
      fullPath: '/app/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/todos': {
      id: '/api/todos'
      path: '/api/todos'
      fullPath: '/api/todos'
      preLoaderRoute: typeof ApiTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/support/': {
      id: '/app/support/'
      path: '/'
      fullPath: '/app/support/'
      preLoaderRoute: typeof AppSupportIndexRouteImport
      parentRoute: typeof AppSupportRoute
    }
    '/app/support/tickets': {
      id: '/app/support/tickets'
      path: '/tickets'
      fullPath: '/app/support/tickets'
      preLoaderRoute: typeof AppSupportTicketsRouteImport
      parentRoute: typeof AppSupportRoute
    }
  }
}

interface AppSupportRouteChildren {
  AppSupportTicketsRoute: typeof AppSupportTicketsRoute
  AppSupportIndexRoute: typeof AppSupportIndexRoute
}

const AppSupportRouteChildren: AppSupportRouteChildren = {
  AppSupportTicketsRoute: AppSupportTicketsRoute,
  AppSupportIndexRoute: AppSupportIndexRoute,
}

const AppSupportRouteWithChildren = AppSupportRoute._addFileChildren(
  AppSupportRouteChildren,
)

interface AppRouteChildren {
  AppSupportRoute: typeof AppSupportRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppSupportRoute: AppSupportRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface FormsRouteChildren {
  FormsAddressRoute: typeof FormsAddressRoute
  FormsSimpleRoute: typeof FormsSimpleRoute
}

const FormsRouteChildren: FormsRouteChildren = {
  FormsAddressRoute: FormsAddressRoute,
  FormsSimpleRoute: FormsSimpleRoute,
}

const FormsRouteWithChildren = FormsRoute._addFileChildren(FormsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DatabaseRoute: DatabaseRoute,
  FormsRoute: FormsRouteWithChildren,
  McpRoute: McpRoute,
  StoreRoute: StoreRoute,
  TableRoute: TableRoute,
  TodosRoute: TodosRoute,
  ApiTodosRoute: ApiTodosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
