/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodosRouteImport } from './routes/todos'
import { Route as TableRouteImport } from './routes/table'
import { Route as StoreRouteImport } from './routes/store'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as FormsRouteImport } from './routes/forms'
import { Route as DatabaseRouteImport } from './routes/database'
import { Route as TenantRouteImport } from './routes/$tenant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FormsSimpleRouteImport } from './routes/forms.simple'
import { Route as FormsAddressRouteImport } from './routes/forms.address'
import { Route as AuthSignUpRouteImport } from './routes/auth.sign-up'
import { Route as ApiTodosRouteImport } from './routes/api.todos'
import { Route as TenantAppRouteImport } from './routes/$tenant.app'
import { Route as ApiUserOrganizationsRouteImport } from './routes/api.user.organizations'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as TenantAppSupportRouteImport } from './routes/$tenant.app.support'
import { Route as TenantAppSalesRouteImport } from './routes/$tenant.app.sales'
import { Route as TenantAppMarketingRouteImport } from './routes/$tenant.app.marketing'
import { Route as TenantAppLoginRouteImport } from './routes/$tenant.app.login'
import { Route as TenantApiUsersRouteImport } from './routes/$tenant.api.users'
import { Route as TenantApiTicketsRouteImport } from './routes/$tenant.api.tickets'
import { Route as TenantApiSubscriptionsRouteImport } from './routes/$tenant.api.subscriptions'
import { Route as TenantApiQuotesRouteImport } from './routes/$tenant.api.quotes'
import { Route as TenantApiPipelinesRouteImport } from './routes/$tenant.api.pipelines'
import { Route as TenantApiMembershipRouteImport } from './routes/$tenant.api.membership'
import { Route as TenantApiMembersRouteImport } from './routes/$tenant.api.members'
import { Route as TenantApiInvoicesRouteImport } from './routes/$tenant.api.invoices'
import { Route as TenantApiDealsRouteImport } from './routes/$tenant.api.deals'
import { Route as TenantApiCouponsRouteImport } from './routes/$tenant.api.coupons'
import { Route as TenantAppSupportIndexRouteImport } from './routes/$tenant.app.support.index'
import { Route as TenantAppSalesIndexRouteImport } from './routes/$tenant.app.sales.index'
import { Route as TenantAppMarketingIndexRouteImport } from './routes/$tenant.app.marketing.index'
import { Route as TenantAppSupportTicketsRouteImport } from './routes/$tenant.app.support.tickets'
import { Route as TenantAppSupportMembersRouteImport } from './routes/$tenant.app.support.members'
import { Route as TenantAppSupportKnowledgeRouteImport } from './routes/$tenant.app.support.knowledge'
import { Route as TenantAppSalesSubscriptionsRouteImport } from './routes/$tenant.app.sales.subscriptions'
import { Route as TenantAppSalesQuotesRouteImport } from './routes/$tenant.app.sales.quotes'
import { Route as TenantAppSalesPromotionsRouteImport } from './routes/$tenant.app.sales.promotions'
import { Route as TenantAppSalesProductCatalogRouteImport } from './routes/$tenant.app.sales.product-catalog'
import { Route as TenantAppSalesPipelineRouteImport } from './routes/$tenant.app.sales.pipeline'
import { Route as TenantAppSalesInvoicesRouteImport } from './routes/$tenant.app.sales.invoices'
import { Route as TenantAppSalesCrmRouteImport } from './routes/$tenant.app.sales.crm'
import { Route as TenantAppSalesAddOnsRouteImport } from './routes/$tenant.app.sales.add-ons'
import { Route as TenantAppMarketingSocialRouteImport } from './routes/$tenant.app.marketing.social'
import { Route as TenantAppMarketingJourneysRouteImport } from './routes/$tenant.app.marketing.journeys'
import { Route as TenantAppMarketingContentRouteImport } from './routes/$tenant.app.marketing.content'
import { Route as TenantAppMarketingCampaignsRouteImport } from './routes/$tenant.app.marketing.campaigns'
import { Route as TenantAppMarketingAudiencesRouteImport } from './routes/$tenant.app.marketing.audiences'
import { Route as TenantAppMarketingAffiliatesRouteImport } from './routes/$tenant.app.marketing.affiliates'
import { Route as TenantApiTicketsTicketIdRouteImport } from './routes/$tenant.api.tickets.$ticketId'
import { Route as TenantApiSubscriptionsSubscriptionIdRouteImport } from './routes/$tenant.api.subscriptions.$subscriptionId'
import { Route as TenantApiSettingsApiKeysRouteImport } from './routes/$tenant.api.settings.api-keys'
import { Route as TenantApiQuotesQuoteIdRouteImport } from './routes/$tenant.api.quotes.$quoteId'
import { Route as TenantApiProductCatalogProductsRouteImport } from './routes/$tenant.api.product-catalog.products'
import { Route as TenantApiProductCatalogPlansRouteImport } from './routes/$tenant.api.product-catalog.plans'
import { Route as TenantApiProductCatalogAddOnsRouteImport } from './routes/$tenant.api.product-catalog.add-ons'
import { Route as TenantApiMembersMemberIdRouteImport } from './routes/$tenant.api.members.$memberId'
import { Route as TenantApiKnowledgeSearchRouteImport } from './routes/$tenant.api.knowledge.search'
import { Route as TenantApiKnowledgePlaybooksRouteImport } from './routes/$tenant.api.knowledge.playbooks'
import { Route as TenantApiKnowledgeArticlesRouteImport } from './routes/$tenant.api.knowledge.articles'
import { Route as TenantApiInvoicesInvoiceIdRouteImport } from './routes/$tenant.api.invoices.$invoiceId'
import { Route as TenantApiDealsDealIdRouteImport } from './routes/$tenant.api.deals.$dealId'
import { Route as TenantApiCrmCustomersRouteImport } from './routes/$tenant.api.crm.customers'
import { Route as TenantApiCrmContactsRouteImport } from './routes/$tenant.api.crm.contacts'
import { Route as TenantApiCouponsValidateRouteImport } from './routes/$tenant.api.coupons.validate'
import { Route as TenantApiCouponsCouponIdRouteImport } from './routes/$tenant.api.coupons.$couponId'
import { Route as TenantAppSupportMembersIndexRouteImport } from './routes/$tenant.app.support.members.index'
import { Route as TenantAppSalesPromotionsIndexRouteImport } from './routes/$tenant.app.sales.promotions.index'
import { Route as TenantAppSalesCrmIndexRouteImport } from './routes/$tenant.app.sales.crm.index'
import { Route as TenantAppSupportOrganizationsOrganizationIdRouteImport } from './routes/$tenant.app.support.organizations.$organizationId'
import { Route as TenantAppSupportMembersMemberIdRouteImport } from './routes/$tenant.app.support.members.$memberId'
import { Route as TenantAppSalesCrmContactsRouteImport } from './routes/$tenant.app.sales.crm.contacts'
import { Route as TenantAppSalesCrmCustomerIdRouteImport } from './routes/$tenant.app.sales.crm.$customerId'
import { Route as TenantApiTicketsTicketIdAuditLogsRouteImport } from './routes/$tenant.api.tickets.$ticketId.audit-logs'
import { Route as TenantApiSupportOrganizationsOrganizationIdRouteImport } from './routes/$tenant.api.support.organizations.$organizationId'
import { Route as TenantApiQuotesQuoteIdSendRouteImport } from './routes/$tenant.api.quotes.$quoteId.send'
import { Route as TenantApiQuotesQuoteIdRejectRouteImport } from './routes/$tenant.api.quotes.$quoteId.reject'
import { Route as TenantApiQuotesQuoteIdPdfRouteImport } from './routes/$tenant.api.quotes.$quoteId.pdf'
import { Route as TenantApiQuotesQuoteIdAcceptRouteImport } from './routes/$tenant.api.quotes.$quoteId.accept'
import { Route as TenantApiProductCatalogPlansPlanIdRouteImport } from './routes/$tenant.api.product-catalog.plans.$planId'
import { Route as TenantApiMembersMemberIdAuditLogsRouteImport } from './routes/$tenant.api.members.$memberId.audit-logs'
import { Route as TenantApiInvoicesInvoiceIdPdfRouteImport } from './routes/$tenant.api.invoices.$invoiceId.pdf'
import { Route as TenantApiInvoicesInvoiceIdPayRouteImport } from './routes/$tenant.api.invoices.$invoiceId.pay'
import { Route as TenantApiInvoicesInvoiceIdFinalizeRouteImport } from './routes/$tenant.api.invoices.$invoiceId.finalize'
import { Route as TenantApiCrmCustomersCustomerIdRouteImport } from './routes/$tenant.api.crm.customers.$customerId'
import { Route as TenantApiCrmContactsContactIdRouteImport } from './routes/$tenant.api.crm.contacts.$contactId'
import { Route as TenantApiCrmCustomersCustomerIdContactsRouteImport } from './routes/$tenant.api.crm.customers.$customerId.contacts'

const TodosRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const TableRoute = TableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsRoute = FormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => rootRouteImport,
} as any)
const DatabaseRoute = DatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantRoute = TenantRouteImport.update({
  id: '/$tenant',
  path: '/$tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsSimpleRoute = FormsSimpleRouteImport.update({
  id: '/simple',
  path: '/simple',
  getParentRoute: () => FormsRoute,
} as any)
const FormsAddressRoute = FormsAddressRouteImport.update({
  id: '/address',
  path: '/address',
  getParentRoute: () => FormsRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTodosRoute = ApiTodosRouteImport.update({
  id: '/api/todos',
  path: '/api/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantAppRoute = TenantAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => TenantRoute,
} as any)
const ApiUserOrganizationsRoute = ApiUserOrganizationsRouteImport.update({
  id: '/api/user/organizations',
  path: '/api/user/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantAppSupportRoute = TenantAppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => TenantAppRoute,
} as any)
const TenantAppSalesRoute = TenantAppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => TenantAppRoute,
} as any)
const TenantAppMarketingRoute = TenantAppMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => TenantAppRoute,
} as any)
const TenantAppLoginRoute = TenantAppLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => TenantAppRoute,
} as any)
const TenantApiUsersRoute = TenantApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => TenantRoute,
} as any)
const TenantApiTicketsRoute = TenantApiTicketsRouteImport.update({
  id: '/api/tickets',
  path: '/api/tickets',
  getParentRoute: () => TenantRoute,
} as any)
const TenantApiSubscriptionsRoute = TenantApiSubscriptionsRouteImport.update({
  id: '/api/subscriptions',
  path: '/api/subscriptions',
  getParentRoute: () => TenantRoute,
} as any)
const TenantApiQuotesRoute = TenantApiQuotesRouteImport.update({
  id: '/api/quotes',
  path: '/api/quotes',
  getParentRoute: () => TenantRoute,
} as any)
const TenantApiPipelinesRoute = TenantApiPipelinesRouteImport.update({
  id: '/api/pipelines',
  path: '/api/pipelines',
  getParentRoute: () => TenantRoute,
} as any)
const TenantApiMembershipRoute = TenantApiMembershipRouteImport.update({
  id: '/api/membership',
  path: '/api/membership',
  getParentRoute: () => TenantRoute,
} as any)
const TenantApiMembersRoute = TenantApiMembersRouteImport.update({
  id: '/api/members',
  path: '/api/members',
  getParentRoute: () => TenantRoute,
} as any)
const TenantApiInvoicesRoute = TenantApiInvoicesRouteImport.update({
  id: '/api/invoices',
  path: '/api/invoices',
  getParentRoute: () => TenantRoute,
} as any)
const TenantApiDealsRoute = TenantApiDealsRouteImport.update({
  id: '/api/deals',
  path: '/api/deals',
  getParentRoute: () => TenantRoute,
} as any)
const TenantApiCouponsRoute = TenantApiCouponsRouteImport.update({
  id: '/api/coupons',
  path: '/api/coupons',
  getParentRoute: () => TenantRoute,
} as any)
const TenantAppSupportIndexRoute = TenantAppSupportIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TenantAppSupportRoute,
} as any)
const TenantAppSalesIndexRoute = TenantAppSalesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TenantAppSalesRoute,
} as any)
const TenantAppMarketingIndexRoute = TenantAppMarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TenantAppMarketingRoute,
} as any)
const TenantAppSupportTicketsRoute = TenantAppSupportTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => TenantAppSupportRoute,
} as any)
const TenantAppSupportMembersRoute = TenantAppSupportMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => TenantAppSupportRoute,
} as any)
const TenantAppSupportKnowledgeRoute =
  TenantAppSupportKnowledgeRouteImport.update({
    id: '/knowledge',
    path: '/knowledge',
    getParentRoute: () => TenantAppSupportRoute,
  } as any)
const TenantAppSalesSubscriptionsRoute =
  TenantAppSalesSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => TenantAppSalesRoute,
  } as any)
const TenantAppSalesQuotesRoute = TenantAppSalesQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => TenantAppSalesRoute,
} as any)
const TenantAppSalesPromotionsRoute =
  TenantAppSalesPromotionsRouteImport.update({
    id: '/promotions',
    path: '/promotions',
    getParentRoute: () => TenantAppSalesRoute,
  } as any)
const TenantAppSalesProductCatalogRoute =
  TenantAppSalesProductCatalogRouteImport.update({
    id: '/product-catalog',
    path: '/product-catalog',
    getParentRoute: () => TenantAppSalesRoute,
  } as any)
const TenantAppSalesPipelineRoute = TenantAppSalesPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => TenantAppSalesRoute,
} as any)
const TenantAppSalesInvoicesRoute = TenantAppSalesInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => TenantAppSalesRoute,
} as any)
const TenantAppSalesCrmRoute = TenantAppSalesCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => TenantAppSalesRoute,
} as any)
const TenantAppSalesAddOnsRoute = TenantAppSalesAddOnsRouteImport.update({
  id: '/add-ons',
  path: '/add-ons',
  getParentRoute: () => TenantAppSalesRoute,
} as any)
const TenantAppMarketingSocialRoute =
  TenantAppMarketingSocialRouteImport.update({
    id: '/social',
    path: '/social',
    getParentRoute: () => TenantAppMarketingRoute,
  } as any)
const TenantAppMarketingJourneysRoute =
  TenantAppMarketingJourneysRouteImport.update({
    id: '/journeys',
    path: '/journeys',
    getParentRoute: () => TenantAppMarketingRoute,
  } as any)
const TenantAppMarketingContentRoute =
  TenantAppMarketingContentRouteImport.update({
    id: '/content',
    path: '/content',
    getParentRoute: () => TenantAppMarketingRoute,
  } as any)
const TenantAppMarketingCampaignsRoute =
  TenantAppMarketingCampaignsRouteImport.update({
    id: '/campaigns',
    path: '/campaigns',
    getParentRoute: () => TenantAppMarketingRoute,
  } as any)
const TenantAppMarketingAudiencesRoute =
  TenantAppMarketingAudiencesRouteImport.update({
    id: '/audiences',
    path: '/audiences',
    getParentRoute: () => TenantAppMarketingRoute,
  } as any)
const TenantAppMarketingAffiliatesRoute =
  TenantAppMarketingAffiliatesRouteImport.update({
    id: '/affiliates',
    path: '/affiliates',
    getParentRoute: () => TenantAppMarketingRoute,
  } as any)
const TenantApiTicketsTicketIdRoute =
  TenantApiTicketsTicketIdRouteImport.update({
    id: '/$ticketId',
    path: '/$ticketId',
    getParentRoute: () => TenantApiTicketsRoute,
  } as any)
const TenantApiSubscriptionsSubscriptionIdRoute =
  TenantApiSubscriptionsSubscriptionIdRouteImport.update({
    id: '/$subscriptionId',
    path: '/$subscriptionId',
    getParentRoute: () => TenantApiSubscriptionsRoute,
  } as any)
const TenantApiSettingsApiKeysRoute =
  TenantApiSettingsApiKeysRouteImport.update({
    id: '/api/settings/api-keys',
    path: '/api/settings/api-keys',
    getParentRoute: () => TenantRoute,
  } as any)
const TenantApiQuotesQuoteIdRoute = TenantApiQuotesQuoteIdRouteImport.update({
  id: '/$quoteId',
  path: '/$quoteId',
  getParentRoute: () => TenantApiQuotesRoute,
} as any)
const TenantApiProductCatalogProductsRoute =
  TenantApiProductCatalogProductsRouteImport.update({
    id: '/api/product-catalog/products',
    path: '/api/product-catalog/products',
    getParentRoute: () => TenantRoute,
  } as any)
const TenantApiProductCatalogPlansRoute =
  TenantApiProductCatalogPlansRouteImport.update({
    id: '/api/product-catalog/plans',
    path: '/api/product-catalog/plans',
    getParentRoute: () => TenantRoute,
  } as any)
const TenantApiProductCatalogAddOnsRoute =
  TenantApiProductCatalogAddOnsRouteImport.update({
    id: '/api/product-catalog/add-ons',
    path: '/api/product-catalog/add-ons',
    getParentRoute: () => TenantRoute,
  } as any)
const TenantApiMembersMemberIdRoute =
  TenantApiMembersMemberIdRouteImport.update({
    id: '/$memberId',
    path: '/$memberId',
    getParentRoute: () => TenantApiMembersRoute,
  } as any)
const TenantApiKnowledgeSearchRoute =
  TenantApiKnowledgeSearchRouteImport.update({
    id: '/api/knowledge/search',
    path: '/api/knowledge/search',
    getParentRoute: () => TenantRoute,
  } as any)
const TenantApiKnowledgePlaybooksRoute =
  TenantApiKnowledgePlaybooksRouteImport.update({
    id: '/api/knowledge/playbooks',
    path: '/api/knowledge/playbooks',
    getParentRoute: () => TenantRoute,
  } as any)
const TenantApiKnowledgeArticlesRoute =
  TenantApiKnowledgeArticlesRouteImport.update({
    id: '/api/knowledge/articles',
    path: '/api/knowledge/articles',
    getParentRoute: () => TenantRoute,
  } as any)
const TenantApiInvoicesInvoiceIdRoute =
  TenantApiInvoicesInvoiceIdRouteImport.update({
    id: '/$invoiceId',
    path: '/$invoiceId',
    getParentRoute: () => TenantApiInvoicesRoute,
  } as any)
const TenantApiDealsDealIdRoute = TenantApiDealsDealIdRouteImport.update({
  id: '/$dealId',
  path: '/$dealId',
  getParentRoute: () => TenantApiDealsRoute,
} as any)
const TenantApiCrmCustomersRoute = TenantApiCrmCustomersRouteImport.update({
  id: '/api/crm/customers',
  path: '/api/crm/customers',
  getParentRoute: () => TenantRoute,
} as any)
const TenantApiCrmContactsRoute = TenantApiCrmContactsRouteImport.update({
  id: '/api/crm/contacts',
  path: '/api/crm/contacts',
  getParentRoute: () => TenantRoute,
} as any)
const TenantApiCouponsValidateRoute =
  TenantApiCouponsValidateRouteImport.update({
    id: '/validate',
    path: '/validate',
    getParentRoute: () => TenantApiCouponsRoute,
  } as any)
const TenantApiCouponsCouponIdRoute =
  TenantApiCouponsCouponIdRouteImport.update({
    id: '/$couponId',
    path: '/$couponId',
    getParentRoute: () => TenantApiCouponsRoute,
  } as any)
const TenantAppSupportMembersIndexRoute =
  TenantAppSupportMembersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TenantAppSupportMembersRoute,
  } as any)
const TenantAppSalesPromotionsIndexRoute =
  TenantAppSalesPromotionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TenantAppSalesPromotionsRoute,
  } as any)
const TenantAppSalesCrmIndexRoute = TenantAppSalesCrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TenantAppSalesCrmRoute,
} as any)
const TenantAppSupportOrganizationsOrganizationIdRoute =
  TenantAppSupportOrganizationsOrganizationIdRouteImport.update({
    id: '/organizations/$organizationId',
    path: '/organizations/$organizationId',
    getParentRoute: () => TenantAppSupportRoute,
  } as any)
const TenantAppSupportMembersMemberIdRoute =
  TenantAppSupportMembersMemberIdRouteImport.update({
    id: '/$memberId',
    path: '/$memberId',
    getParentRoute: () => TenantAppSupportMembersRoute,
  } as any)
const TenantAppSalesCrmContactsRoute =
  TenantAppSalesCrmContactsRouteImport.update({
    id: '/contacts',
    path: '/contacts',
    getParentRoute: () => TenantAppSalesCrmRoute,
  } as any)
const TenantAppSalesCrmCustomerIdRoute =
  TenantAppSalesCrmCustomerIdRouteImport.update({
    id: '/$customerId',
    path: '/$customerId',
    getParentRoute: () => TenantAppSalesCrmRoute,
  } as any)
const TenantApiTicketsTicketIdAuditLogsRoute =
  TenantApiTicketsTicketIdAuditLogsRouteImport.update({
    id: '/audit-logs',
    path: '/audit-logs',
    getParentRoute: () => TenantApiTicketsTicketIdRoute,
  } as any)
const TenantApiSupportOrganizationsOrganizationIdRoute =
  TenantApiSupportOrganizationsOrganizationIdRouteImport.update({
    id: '/api/support/organizations/$organizationId',
    path: '/api/support/organizations/$organizationId',
    getParentRoute: () => TenantRoute,
  } as any)
const TenantApiQuotesQuoteIdSendRoute =
  TenantApiQuotesQuoteIdSendRouteImport.update({
    id: '/send',
    path: '/send',
    getParentRoute: () => TenantApiQuotesQuoteIdRoute,
  } as any)
const TenantApiQuotesQuoteIdRejectRoute =
  TenantApiQuotesQuoteIdRejectRouteImport.update({
    id: '/reject',
    path: '/reject',
    getParentRoute: () => TenantApiQuotesQuoteIdRoute,
  } as any)
const TenantApiQuotesQuoteIdPdfRoute =
  TenantApiQuotesQuoteIdPdfRouteImport.update({
    id: '/pdf',
    path: '/pdf',
    getParentRoute: () => TenantApiQuotesQuoteIdRoute,
  } as any)
const TenantApiQuotesQuoteIdAcceptRoute =
  TenantApiQuotesQuoteIdAcceptRouteImport.update({
    id: '/accept',
    path: '/accept',
    getParentRoute: () => TenantApiQuotesQuoteIdRoute,
  } as any)
const TenantApiProductCatalogPlansPlanIdRoute =
  TenantApiProductCatalogPlansPlanIdRouteImport.update({
    id: '/$planId',
    path: '/$planId',
    getParentRoute: () => TenantApiProductCatalogPlansRoute,
  } as any)
const TenantApiMembersMemberIdAuditLogsRoute =
  TenantApiMembersMemberIdAuditLogsRouteImport.update({
    id: '/audit-logs',
    path: '/audit-logs',
    getParentRoute: () => TenantApiMembersMemberIdRoute,
  } as any)
const TenantApiInvoicesInvoiceIdPdfRoute =
  TenantApiInvoicesInvoiceIdPdfRouteImport.update({
    id: '/pdf',
    path: '/pdf',
    getParentRoute: () => TenantApiInvoicesInvoiceIdRoute,
  } as any)
const TenantApiInvoicesInvoiceIdPayRoute =
  TenantApiInvoicesInvoiceIdPayRouteImport.update({
    id: '/pay',
    path: '/pay',
    getParentRoute: () => TenantApiInvoicesInvoiceIdRoute,
  } as any)
const TenantApiInvoicesInvoiceIdFinalizeRoute =
  TenantApiInvoicesInvoiceIdFinalizeRouteImport.update({
    id: '/finalize',
    path: '/finalize',
    getParentRoute: () => TenantApiInvoicesInvoiceIdRoute,
  } as any)
const TenantApiCrmCustomersCustomerIdRoute =
  TenantApiCrmCustomersCustomerIdRouteImport.update({
    id: '/$customerId',
    path: '/$customerId',
    getParentRoute: () => TenantApiCrmCustomersRoute,
  } as any)
const TenantApiCrmContactsContactIdRoute =
  TenantApiCrmContactsContactIdRouteImport.update({
    id: '/$contactId',
    path: '/$contactId',
    getParentRoute: () => TenantApiCrmContactsRoute,
  } as any)
const TenantApiCrmCustomersCustomerIdContactsRoute =
  TenantApiCrmCustomersCustomerIdContactsRouteImport.update({
    id: '/contacts',
    path: '/contacts',
    getParentRoute: () => TenantApiCrmCustomersCustomerIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$tenant': typeof TenantRouteWithChildren
  '/database': typeof DatabaseRoute
  '/forms': typeof FormsRouteWithChildren
  '/mcp': typeof McpRoute
  '/store': typeof StoreRoute
  '/table': typeof TableRoute
  '/todos': typeof TodosRoute
  '/$tenant/app': typeof TenantAppRouteWithChildren
  '/api/todos': typeof ApiTodosRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/forms/address': typeof FormsAddressRoute
  '/forms/simple': typeof FormsSimpleRoute
  '/$tenant/api/coupons': typeof TenantApiCouponsRouteWithChildren
  '/$tenant/api/deals': typeof TenantApiDealsRouteWithChildren
  '/$tenant/api/invoices': typeof TenantApiInvoicesRouteWithChildren
  '/$tenant/api/members': typeof TenantApiMembersRouteWithChildren
  '/$tenant/api/membership': typeof TenantApiMembershipRoute
  '/$tenant/api/pipelines': typeof TenantApiPipelinesRoute
  '/$tenant/api/quotes': typeof TenantApiQuotesRouteWithChildren
  '/$tenant/api/subscriptions': typeof TenantApiSubscriptionsRouteWithChildren
  '/$tenant/api/tickets': typeof TenantApiTicketsRouteWithChildren
  '/$tenant/api/users': typeof TenantApiUsersRoute
  '/$tenant/app/login': typeof TenantAppLoginRoute
  '/$tenant/app/marketing': typeof TenantAppMarketingRouteWithChildren
  '/$tenant/app/sales': typeof TenantAppSalesRouteWithChildren
  '/$tenant/app/support': typeof TenantAppSupportRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/user/organizations': typeof ApiUserOrganizationsRoute
  '/$tenant/api/coupons/$couponId': typeof TenantApiCouponsCouponIdRoute
  '/$tenant/api/coupons/validate': typeof TenantApiCouponsValidateRoute
  '/$tenant/api/crm/contacts': typeof TenantApiCrmContactsRouteWithChildren
  '/$tenant/api/crm/customers': typeof TenantApiCrmCustomersRouteWithChildren
  '/$tenant/api/deals/$dealId': typeof TenantApiDealsDealIdRoute
  '/$tenant/api/invoices/$invoiceId': typeof TenantApiInvoicesInvoiceIdRouteWithChildren
  '/$tenant/api/knowledge/articles': typeof TenantApiKnowledgeArticlesRoute
  '/$tenant/api/knowledge/playbooks': typeof TenantApiKnowledgePlaybooksRoute
  '/$tenant/api/knowledge/search': typeof TenantApiKnowledgeSearchRoute
  '/$tenant/api/members/$memberId': typeof TenantApiMembersMemberIdRouteWithChildren
  '/$tenant/api/product-catalog/add-ons': typeof TenantApiProductCatalogAddOnsRoute
  '/$tenant/api/product-catalog/plans': typeof TenantApiProductCatalogPlansRouteWithChildren
  '/$tenant/api/product-catalog/products': typeof TenantApiProductCatalogProductsRoute
  '/$tenant/api/quotes/$quoteId': typeof TenantApiQuotesQuoteIdRouteWithChildren
  '/$tenant/api/settings/api-keys': typeof TenantApiSettingsApiKeysRoute
  '/$tenant/api/subscriptions/$subscriptionId': typeof TenantApiSubscriptionsSubscriptionIdRoute
  '/$tenant/api/tickets/$ticketId': typeof TenantApiTicketsTicketIdRouteWithChildren
  '/$tenant/app/marketing/affiliates': typeof TenantAppMarketingAffiliatesRoute
  '/$tenant/app/marketing/audiences': typeof TenantAppMarketingAudiencesRoute
  '/$tenant/app/marketing/campaigns': typeof TenantAppMarketingCampaignsRoute
  '/$tenant/app/marketing/content': typeof TenantAppMarketingContentRoute
  '/$tenant/app/marketing/journeys': typeof TenantAppMarketingJourneysRoute
  '/$tenant/app/marketing/social': typeof TenantAppMarketingSocialRoute
  '/$tenant/app/sales/add-ons': typeof TenantAppSalesAddOnsRoute
  '/$tenant/app/sales/crm': typeof TenantAppSalesCrmRouteWithChildren
  '/$tenant/app/sales/invoices': typeof TenantAppSalesInvoicesRoute
  '/$tenant/app/sales/pipeline': typeof TenantAppSalesPipelineRoute
  '/$tenant/app/sales/product-catalog': typeof TenantAppSalesProductCatalogRoute
  '/$tenant/app/sales/promotions': typeof TenantAppSalesPromotionsRouteWithChildren
  '/$tenant/app/sales/quotes': typeof TenantAppSalesQuotesRoute
  '/$tenant/app/sales/subscriptions': typeof TenantAppSalesSubscriptionsRoute
  '/$tenant/app/support/knowledge': typeof TenantAppSupportKnowledgeRoute
  '/$tenant/app/support/members': typeof TenantAppSupportMembersRouteWithChildren
  '/$tenant/app/support/tickets': typeof TenantAppSupportTicketsRoute
  '/$tenant/app/marketing/': typeof TenantAppMarketingIndexRoute
  '/$tenant/app/sales/': typeof TenantAppSalesIndexRoute
  '/$tenant/app/support/': typeof TenantAppSupportIndexRoute
  '/$tenant/api/crm/contacts/$contactId': typeof TenantApiCrmContactsContactIdRoute
  '/$tenant/api/crm/customers/$customerId': typeof TenantApiCrmCustomersCustomerIdRouteWithChildren
  '/$tenant/api/invoices/$invoiceId/finalize': typeof TenantApiInvoicesInvoiceIdFinalizeRoute
  '/$tenant/api/invoices/$invoiceId/pay': typeof TenantApiInvoicesInvoiceIdPayRoute
  '/$tenant/api/invoices/$invoiceId/pdf': typeof TenantApiInvoicesInvoiceIdPdfRoute
  '/$tenant/api/members/$memberId/audit-logs': typeof TenantApiMembersMemberIdAuditLogsRoute
  '/$tenant/api/product-catalog/plans/$planId': typeof TenantApiProductCatalogPlansPlanIdRoute
  '/$tenant/api/quotes/$quoteId/accept': typeof TenantApiQuotesQuoteIdAcceptRoute
  '/$tenant/api/quotes/$quoteId/pdf': typeof TenantApiQuotesQuoteIdPdfRoute
  '/$tenant/api/quotes/$quoteId/reject': typeof TenantApiQuotesQuoteIdRejectRoute
  '/$tenant/api/quotes/$quoteId/send': typeof TenantApiQuotesQuoteIdSendRoute
  '/$tenant/api/support/organizations/$organizationId': typeof TenantApiSupportOrganizationsOrganizationIdRoute
  '/$tenant/api/tickets/$ticketId/audit-logs': typeof TenantApiTicketsTicketIdAuditLogsRoute
  '/$tenant/app/sales/crm/$customerId': typeof TenantAppSalesCrmCustomerIdRoute
  '/$tenant/app/sales/crm/contacts': typeof TenantAppSalesCrmContactsRoute
  '/$tenant/app/support/members/$memberId': typeof TenantAppSupportMembersMemberIdRoute
  '/$tenant/app/support/organizations/$organizationId': typeof TenantAppSupportOrganizationsOrganizationIdRoute
  '/$tenant/app/sales/crm/': typeof TenantAppSalesCrmIndexRoute
  '/$tenant/app/sales/promotions/': typeof TenantAppSalesPromotionsIndexRoute
  '/$tenant/app/support/members/': typeof TenantAppSupportMembersIndexRoute
  '/$tenant/api/crm/customers/$customerId/contacts': typeof TenantApiCrmCustomersCustomerIdContactsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$tenant': typeof TenantRouteWithChildren
  '/database': typeof DatabaseRoute
  '/forms': typeof FormsRouteWithChildren
  '/mcp': typeof McpRoute
  '/store': typeof StoreRoute
  '/table': typeof TableRoute
  '/todos': typeof TodosRoute
  '/$tenant/app': typeof TenantAppRouteWithChildren
  '/api/todos': typeof ApiTodosRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/forms/address': typeof FormsAddressRoute
  '/forms/simple': typeof FormsSimpleRoute
  '/$tenant/api/coupons': typeof TenantApiCouponsRouteWithChildren
  '/$tenant/api/deals': typeof TenantApiDealsRouteWithChildren
  '/$tenant/api/invoices': typeof TenantApiInvoicesRouteWithChildren
  '/$tenant/api/members': typeof TenantApiMembersRouteWithChildren
  '/$tenant/api/membership': typeof TenantApiMembershipRoute
  '/$tenant/api/pipelines': typeof TenantApiPipelinesRoute
  '/$tenant/api/quotes': typeof TenantApiQuotesRouteWithChildren
  '/$tenant/api/subscriptions': typeof TenantApiSubscriptionsRouteWithChildren
  '/$tenant/api/tickets': typeof TenantApiTicketsRouteWithChildren
  '/$tenant/api/users': typeof TenantApiUsersRoute
  '/$tenant/app/login': typeof TenantAppLoginRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/user/organizations': typeof ApiUserOrganizationsRoute
  '/$tenant/api/coupons/$couponId': typeof TenantApiCouponsCouponIdRoute
  '/$tenant/api/coupons/validate': typeof TenantApiCouponsValidateRoute
  '/$tenant/api/crm/contacts': typeof TenantApiCrmContactsRouteWithChildren
  '/$tenant/api/crm/customers': typeof TenantApiCrmCustomersRouteWithChildren
  '/$tenant/api/deals/$dealId': typeof TenantApiDealsDealIdRoute
  '/$tenant/api/invoices/$invoiceId': typeof TenantApiInvoicesInvoiceIdRouteWithChildren
  '/$tenant/api/knowledge/articles': typeof TenantApiKnowledgeArticlesRoute
  '/$tenant/api/knowledge/playbooks': typeof TenantApiKnowledgePlaybooksRoute
  '/$tenant/api/knowledge/search': typeof TenantApiKnowledgeSearchRoute
  '/$tenant/api/members/$memberId': typeof TenantApiMembersMemberIdRouteWithChildren
  '/$tenant/api/product-catalog/add-ons': typeof TenantApiProductCatalogAddOnsRoute
  '/$tenant/api/product-catalog/plans': typeof TenantApiProductCatalogPlansRouteWithChildren
  '/$tenant/api/product-catalog/products': typeof TenantApiProductCatalogProductsRoute
  '/$tenant/api/quotes/$quoteId': typeof TenantApiQuotesQuoteIdRouteWithChildren
  '/$tenant/api/settings/api-keys': typeof TenantApiSettingsApiKeysRoute
  '/$tenant/api/subscriptions/$subscriptionId': typeof TenantApiSubscriptionsSubscriptionIdRoute
  '/$tenant/api/tickets/$ticketId': typeof TenantApiTicketsTicketIdRouteWithChildren
  '/$tenant/app/marketing/affiliates': typeof TenantAppMarketingAffiliatesRoute
  '/$tenant/app/marketing/audiences': typeof TenantAppMarketingAudiencesRoute
  '/$tenant/app/marketing/campaigns': typeof TenantAppMarketingCampaignsRoute
  '/$tenant/app/marketing/content': typeof TenantAppMarketingContentRoute
  '/$tenant/app/marketing/journeys': typeof TenantAppMarketingJourneysRoute
  '/$tenant/app/marketing/social': typeof TenantAppMarketingSocialRoute
  '/$tenant/app/sales/add-ons': typeof TenantAppSalesAddOnsRoute
  '/$tenant/app/sales/invoices': typeof TenantAppSalesInvoicesRoute
  '/$tenant/app/sales/pipeline': typeof TenantAppSalesPipelineRoute
  '/$tenant/app/sales/product-catalog': typeof TenantAppSalesProductCatalogRoute
  '/$tenant/app/sales/quotes': typeof TenantAppSalesQuotesRoute
  '/$tenant/app/sales/subscriptions': typeof TenantAppSalesSubscriptionsRoute
  '/$tenant/app/support/knowledge': typeof TenantAppSupportKnowledgeRoute
  '/$tenant/app/support/tickets': typeof TenantAppSupportTicketsRoute
  '/$tenant/app/marketing': typeof TenantAppMarketingIndexRoute
  '/$tenant/app/sales': typeof TenantAppSalesIndexRoute
  '/$tenant/app/support': typeof TenantAppSupportIndexRoute
  '/$tenant/api/crm/contacts/$contactId': typeof TenantApiCrmContactsContactIdRoute
  '/$tenant/api/crm/customers/$customerId': typeof TenantApiCrmCustomersCustomerIdRouteWithChildren
  '/$tenant/api/invoices/$invoiceId/finalize': typeof TenantApiInvoicesInvoiceIdFinalizeRoute
  '/$tenant/api/invoices/$invoiceId/pay': typeof TenantApiInvoicesInvoiceIdPayRoute
  '/$tenant/api/invoices/$invoiceId/pdf': typeof TenantApiInvoicesInvoiceIdPdfRoute
  '/$tenant/api/members/$memberId/audit-logs': typeof TenantApiMembersMemberIdAuditLogsRoute
  '/$tenant/api/product-catalog/plans/$planId': typeof TenantApiProductCatalogPlansPlanIdRoute
  '/$tenant/api/quotes/$quoteId/accept': typeof TenantApiQuotesQuoteIdAcceptRoute
  '/$tenant/api/quotes/$quoteId/pdf': typeof TenantApiQuotesQuoteIdPdfRoute
  '/$tenant/api/quotes/$quoteId/reject': typeof TenantApiQuotesQuoteIdRejectRoute
  '/$tenant/api/quotes/$quoteId/send': typeof TenantApiQuotesQuoteIdSendRoute
  '/$tenant/api/support/organizations/$organizationId': typeof TenantApiSupportOrganizationsOrganizationIdRoute
  '/$tenant/api/tickets/$ticketId/audit-logs': typeof TenantApiTicketsTicketIdAuditLogsRoute
  '/$tenant/app/sales/crm/$customerId': typeof TenantAppSalesCrmCustomerIdRoute
  '/$tenant/app/sales/crm/contacts': typeof TenantAppSalesCrmContactsRoute
  '/$tenant/app/support/members/$memberId': typeof TenantAppSupportMembersMemberIdRoute
  '/$tenant/app/support/organizations/$organizationId': typeof TenantAppSupportOrganizationsOrganizationIdRoute
  '/$tenant/app/sales/crm': typeof TenantAppSalesCrmIndexRoute
  '/$tenant/app/sales/promotions': typeof TenantAppSalesPromotionsIndexRoute
  '/$tenant/app/support/members': typeof TenantAppSupportMembersIndexRoute
  '/$tenant/api/crm/customers/$customerId/contacts': typeof TenantApiCrmCustomersCustomerIdContactsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$tenant': typeof TenantRouteWithChildren
  '/database': typeof DatabaseRoute
  '/forms': typeof FormsRouteWithChildren
  '/mcp': typeof McpRoute
  '/store': typeof StoreRoute
  '/table': typeof TableRoute
  '/todos': typeof TodosRoute
  '/$tenant/app': typeof TenantAppRouteWithChildren
  '/api/todos': typeof ApiTodosRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/forms/address': typeof FormsAddressRoute
  '/forms/simple': typeof FormsSimpleRoute
  '/$tenant/api/coupons': typeof TenantApiCouponsRouteWithChildren
  '/$tenant/api/deals': typeof TenantApiDealsRouteWithChildren
  '/$tenant/api/invoices': typeof TenantApiInvoicesRouteWithChildren
  '/$tenant/api/members': typeof TenantApiMembersRouteWithChildren
  '/$tenant/api/membership': typeof TenantApiMembershipRoute
  '/$tenant/api/pipelines': typeof TenantApiPipelinesRoute
  '/$tenant/api/quotes': typeof TenantApiQuotesRouteWithChildren
  '/$tenant/api/subscriptions': typeof TenantApiSubscriptionsRouteWithChildren
  '/$tenant/api/tickets': typeof TenantApiTicketsRouteWithChildren
  '/$tenant/api/users': typeof TenantApiUsersRoute
  '/$tenant/app/login': typeof TenantAppLoginRoute
  '/$tenant/app/marketing': typeof TenantAppMarketingRouteWithChildren
  '/$tenant/app/sales': typeof TenantAppSalesRouteWithChildren
  '/$tenant/app/support': typeof TenantAppSupportRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/user/organizations': typeof ApiUserOrganizationsRoute
  '/$tenant/api/coupons/$couponId': typeof TenantApiCouponsCouponIdRoute
  '/$tenant/api/coupons/validate': typeof TenantApiCouponsValidateRoute
  '/$tenant/api/crm/contacts': typeof TenantApiCrmContactsRouteWithChildren
  '/$tenant/api/crm/customers': typeof TenantApiCrmCustomersRouteWithChildren
  '/$tenant/api/deals/$dealId': typeof TenantApiDealsDealIdRoute
  '/$tenant/api/invoices/$invoiceId': typeof TenantApiInvoicesInvoiceIdRouteWithChildren
  '/$tenant/api/knowledge/articles': typeof TenantApiKnowledgeArticlesRoute
  '/$tenant/api/knowledge/playbooks': typeof TenantApiKnowledgePlaybooksRoute
  '/$tenant/api/knowledge/search': typeof TenantApiKnowledgeSearchRoute
  '/$tenant/api/members/$memberId': typeof TenantApiMembersMemberIdRouteWithChildren
  '/$tenant/api/product-catalog/add-ons': typeof TenantApiProductCatalogAddOnsRoute
  '/$tenant/api/product-catalog/plans': typeof TenantApiProductCatalogPlansRouteWithChildren
  '/$tenant/api/product-catalog/products': typeof TenantApiProductCatalogProductsRoute
  '/$tenant/api/quotes/$quoteId': typeof TenantApiQuotesQuoteIdRouteWithChildren
  '/$tenant/api/settings/api-keys': typeof TenantApiSettingsApiKeysRoute
  '/$tenant/api/subscriptions/$subscriptionId': typeof TenantApiSubscriptionsSubscriptionIdRoute
  '/$tenant/api/tickets/$ticketId': typeof TenantApiTicketsTicketIdRouteWithChildren
  '/$tenant/app/marketing/affiliates': typeof TenantAppMarketingAffiliatesRoute
  '/$tenant/app/marketing/audiences': typeof TenantAppMarketingAudiencesRoute
  '/$tenant/app/marketing/campaigns': typeof TenantAppMarketingCampaignsRoute
  '/$tenant/app/marketing/content': typeof TenantAppMarketingContentRoute
  '/$tenant/app/marketing/journeys': typeof TenantAppMarketingJourneysRoute
  '/$tenant/app/marketing/social': typeof TenantAppMarketingSocialRoute
  '/$tenant/app/sales/add-ons': typeof TenantAppSalesAddOnsRoute
  '/$tenant/app/sales/crm': typeof TenantAppSalesCrmRouteWithChildren
  '/$tenant/app/sales/invoices': typeof TenantAppSalesInvoicesRoute
  '/$tenant/app/sales/pipeline': typeof TenantAppSalesPipelineRoute
  '/$tenant/app/sales/product-catalog': typeof TenantAppSalesProductCatalogRoute
  '/$tenant/app/sales/promotions': typeof TenantAppSalesPromotionsRouteWithChildren
  '/$tenant/app/sales/quotes': typeof TenantAppSalesQuotesRoute
  '/$tenant/app/sales/subscriptions': typeof TenantAppSalesSubscriptionsRoute
  '/$tenant/app/support/knowledge': typeof TenantAppSupportKnowledgeRoute
  '/$tenant/app/support/members': typeof TenantAppSupportMembersRouteWithChildren
  '/$tenant/app/support/tickets': typeof TenantAppSupportTicketsRoute
  '/$tenant/app/marketing/': typeof TenantAppMarketingIndexRoute
  '/$tenant/app/sales/': typeof TenantAppSalesIndexRoute
  '/$tenant/app/support/': typeof TenantAppSupportIndexRoute
  '/$tenant/api/crm/contacts/$contactId': typeof TenantApiCrmContactsContactIdRoute
  '/$tenant/api/crm/customers/$customerId': typeof TenantApiCrmCustomersCustomerIdRouteWithChildren
  '/$tenant/api/invoices/$invoiceId/finalize': typeof TenantApiInvoicesInvoiceIdFinalizeRoute
  '/$tenant/api/invoices/$invoiceId/pay': typeof TenantApiInvoicesInvoiceIdPayRoute
  '/$tenant/api/invoices/$invoiceId/pdf': typeof TenantApiInvoicesInvoiceIdPdfRoute
  '/$tenant/api/members/$memberId/audit-logs': typeof TenantApiMembersMemberIdAuditLogsRoute
  '/$tenant/api/product-catalog/plans/$planId': typeof TenantApiProductCatalogPlansPlanIdRoute
  '/$tenant/api/quotes/$quoteId/accept': typeof TenantApiQuotesQuoteIdAcceptRoute
  '/$tenant/api/quotes/$quoteId/pdf': typeof TenantApiQuotesQuoteIdPdfRoute
  '/$tenant/api/quotes/$quoteId/reject': typeof TenantApiQuotesQuoteIdRejectRoute
  '/$tenant/api/quotes/$quoteId/send': typeof TenantApiQuotesQuoteIdSendRoute
  '/$tenant/api/support/organizations/$organizationId': typeof TenantApiSupportOrganizationsOrganizationIdRoute
  '/$tenant/api/tickets/$ticketId/audit-logs': typeof TenantApiTicketsTicketIdAuditLogsRoute
  '/$tenant/app/sales/crm/$customerId': typeof TenantAppSalesCrmCustomerIdRoute
  '/$tenant/app/sales/crm/contacts': typeof TenantAppSalesCrmContactsRoute
  '/$tenant/app/support/members/$memberId': typeof TenantAppSupportMembersMemberIdRoute
  '/$tenant/app/support/organizations/$organizationId': typeof TenantAppSupportOrganizationsOrganizationIdRoute
  '/$tenant/app/sales/crm/': typeof TenantAppSalesCrmIndexRoute
  '/$tenant/app/sales/promotions/': typeof TenantAppSalesPromotionsIndexRoute
  '/$tenant/app/support/members/': typeof TenantAppSupportMembersIndexRoute
  '/$tenant/api/crm/customers/$customerId/contacts': typeof TenantApiCrmCustomersCustomerIdContactsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$tenant'
    | '/database'
    | '/forms'
    | '/mcp'
    | '/store'
    | '/table'
    | '/todos'
    | '/$tenant/app'
    | '/api/todos'
    | '/auth/sign-up'
    | '/forms/address'
    | '/forms/simple'
    | '/$tenant/api/coupons'
    | '/$tenant/api/deals'
    | '/$tenant/api/invoices'
    | '/$tenant/api/members'
    | '/$tenant/api/membership'
    | '/$tenant/api/pipelines'
    | '/$tenant/api/quotes'
    | '/$tenant/api/subscriptions'
    | '/$tenant/api/tickets'
    | '/$tenant/api/users'
    | '/$tenant/app/login'
    | '/$tenant/app/marketing'
    | '/$tenant/app/sales'
    | '/$tenant/app/support'
    | '/api/auth/$'
    | '/api/user/organizations'
    | '/$tenant/api/coupons/$couponId'
    | '/$tenant/api/coupons/validate'
    | '/$tenant/api/crm/contacts'
    | '/$tenant/api/crm/customers'
    | '/$tenant/api/deals/$dealId'
    | '/$tenant/api/invoices/$invoiceId'
    | '/$tenant/api/knowledge/articles'
    | '/$tenant/api/knowledge/playbooks'
    | '/$tenant/api/knowledge/search'
    | '/$tenant/api/members/$memberId'
    | '/$tenant/api/product-catalog/add-ons'
    | '/$tenant/api/product-catalog/plans'
    | '/$tenant/api/product-catalog/products'
    | '/$tenant/api/quotes/$quoteId'
    | '/$tenant/api/settings/api-keys'
    | '/$tenant/api/subscriptions/$subscriptionId'
    | '/$tenant/api/tickets/$ticketId'
    | '/$tenant/app/marketing/affiliates'
    | '/$tenant/app/marketing/audiences'
    | '/$tenant/app/marketing/campaigns'
    | '/$tenant/app/marketing/content'
    | '/$tenant/app/marketing/journeys'
    | '/$tenant/app/marketing/social'
    | '/$tenant/app/sales/add-ons'
    | '/$tenant/app/sales/crm'
    | '/$tenant/app/sales/invoices'
    | '/$tenant/app/sales/pipeline'
    | '/$tenant/app/sales/product-catalog'
    | '/$tenant/app/sales/promotions'
    | '/$tenant/app/sales/quotes'
    | '/$tenant/app/sales/subscriptions'
    | '/$tenant/app/support/knowledge'
    | '/$tenant/app/support/members'
    | '/$tenant/app/support/tickets'
    | '/$tenant/app/marketing/'
    | '/$tenant/app/sales/'
    | '/$tenant/app/support/'
    | '/$tenant/api/crm/contacts/$contactId'
    | '/$tenant/api/crm/customers/$customerId'
    | '/$tenant/api/invoices/$invoiceId/finalize'
    | '/$tenant/api/invoices/$invoiceId/pay'
    | '/$tenant/api/invoices/$invoiceId/pdf'
    | '/$tenant/api/members/$memberId/audit-logs'
    | '/$tenant/api/product-catalog/plans/$planId'
    | '/$tenant/api/quotes/$quoteId/accept'
    | '/$tenant/api/quotes/$quoteId/pdf'
    | '/$tenant/api/quotes/$quoteId/reject'
    | '/$tenant/api/quotes/$quoteId/send'
    | '/$tenant/api/support/organizations/$organizationId'
    | '/$tenant/api/tickets/$ticketId/audit-logs'
    | '/$tenant/app/sales/crm/$customerId'
    | '/$tenant/app/sales/crm/contacts'
    | '/$tenant/app/support/members/$memberId'
    | '/$tenant/app/support/organizations/$organizationId'
    | '/$tenant/app/sales/crm/'
    | '/$tenant/app/sales/promotions/'
    | '/$tenant/app/support/members/'
    | '/$tenant/api/crm/customers/$customerId/contacts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$tenant'
    | '/database'
    | '/forms'
    | '/mcp'
    | '/store'
    | '/table'
    | '/todos'
    | '/$tenant/app'
    | '/api/todos'
    | '/auth/sign-up'
    | '/forms/address'
    | '/forms/simple'
    | '/$tenant/api/coupons'
    | '/$tenant/api/deals'
    | '/$tenant/api/invoices'
    | '/$tenant/api/members'
    | '/$tenant/api/membership'
    | '/$tenant/api/pipelines'
    | '/$tenant/api/quotes'
    | '/$tenant/api/subscriptions'
    | '/$tenant/api/tickets'
    | '/$tenant/api/users'
    | '/$tenant/app/login'
    | '/api/auth/$'
    | '/api/user/organizations'
    | '/$tenant/api/coupons/$couponId'
    | '/$tenant/api/coupons/validate'
    | '/$tenant/api/crm/contacts'
    | '/$tenant/api/crm/customers'
    | '/$tenant/api/deals/$dealId'
    | '/$tenant/api/invoices/$invoiceId'
    | '/$tenant/api/knowledge/articles'
    | '/$tenant/api/knowledge/playbooks'
    | '/$tenant/api/knowledge/search'
    | '/$tenant/api/members/$memberId'
    | '/$tenant/api/product-catalog/add-ons'
    | '/$tenant/api/product-catalog/plans'
    | '/$tenant/api/product-catalog/products'
    | '/$tenant/api/quotes/$quoteId'
    | '/$tenant/api/settings/api-keys'
    | '/$tenant/api/subscriptions/$subscriptionId'
    | '/$tenant/api/tickets/$ticketId'
    | '/$tenant/app/marketing/affiliates'
    | '/$tenant/app/marketing/audiences'
    | '/$tenant/app/marketing/campaigns'
    | '/$tenant/app/marketing/content'
    | '/$tenant/app/marketing/journeys'
    | '/$tenant/app/marketing/social'
    | '/$tenant/app/sales/add-ons'
    | '/$tenant/app/sales/invoices'
    | '/$tenant/app/sales/pipeline'
    | '/$tenant/app/sales/product-catalog'
    | '/$tenant/app/sales/quotes'
    | '/$tenant/app/sales/subscriptions'
    | '/$tenant/app/support/knowledge'
    | '/$tenant/app/support/tickets'
    | '/$tenant/app/marketing'
    | '/$tenant/app/sales'
    | '/$tenant/app/support'
    | '/$tenant/api/crm/contacts/$contactId'
    | '/$tenant/api/crm/customers/$customerId'
    | '/$tenant/api/invoices/$invoiceId/finalize'
    | '/$tenant/api/invoices/$invoiceId/pay'
    | '/$tenant/api/invoices/$invoiceId/pdf'
    | '/$tenant/api/members/$memberId/audit-logs'
    | '/$tenant/api/product-catalog/plans/$planId'
    | '/$tenant/api/quotes/$quoteId/accept'
    | '/$tenant/api/quotes/$quoteId/pdf'
    | '/$tenant/api/quotes/$quoteId/reject'
    | '/$tenant/api/quotes/$quoteId/send'
    | '/$tenant/api/support/organizations/$organizationId'
    | '/$tenant/api/tickets/$ticketId/audit-logs'
    | '/$tenant/app/sales/crm/$customerId'
    | '/$tenant/app/sales/crm/contacts'
    | '/$tenant/app/support/members/$memberId'
    | '/$tenant/app/support/organizations/$organizationId'
    | '/$tenant/app/sales/crm'
    | '/$tenant/app/sales/promotions'
    | '/$tenant/app/support/members'
    | '/$tenant/api/crm/customers/$customerId/contacts'
  id:
    | '__root__'
    | '/'
    | '/$tenant'
    | '/database'
    | '/forms'
    | '/mcp'
    | '/store'
    | '/table'
    | '/todos'
    | '/$tenant/app'
    | '/api/todos'
    | '/auth/sign-up'
    | '/forms/address'
    | '/forms/simple'
    | '/$tenant/api/coupons'
    | '/$tenant/api/deals'
    | '/$tenant/api/invoices'
    | '/$tenant/api/members'
    | '/$tenant/api/membership'
    | '/$tenant/api/pipelines'
    | '/$tenant/api/quotes'
    | '/$tenant/api/subscriptions'
    | '/$tenant/api/tickets'
    | '/$tenant/api/users'
    | '/$tenant/app/login'
    | '/$tenant/app/marketing'
    | '/$tenant/app/sales'
    | '/$tenant/app/support'
    | '/api/auth/$'
    | '/api/user/organizations'
    | '/$tenant/api/coupons/$couponId'
    | '/$tenant/api/coupons/validate'
    | '/$tenant/api/crm/contacts'
    | '/$tenant/api/crm/customers'
    | '/$tenant/api/deals/$dealId'
    | '/$tenant/api/invoices/$invoiceId'
    | '/$tenant/api/knowledge/articles'
    | '/$tenant/api/knowledge/playbooks'
    | '/$tenant/api/knowledge/search'
    | '/$tenant/api/members/$memberId'
    | '/$tenant/api/product-catalog/add-ons'
    | '/$tenant/api/product-catalog/plans'
    | '/$tenant/api/product-catalog/products'
    | '/$tenant/api/quotes/$quoteId'
    | '/$tenant/api/settings/api-keys'
    | '/$tenant/api/subscriptions/$subscriptionId'
    | '/$tenant/api/tickets/$ticketId'
    | '/$tenant/app/marketing/affiliates'
    | '/$tenant/app/marketing/audiences'
    | '/$tenant/app/marketing/campaigns'
    | '/$tenant/app/marketing/content'
    | '/$tenant/app/marketing/journeys'
    | '/$tenant/app/marketing/social'
    | '/$tenant/app/sales/add-ons'
    | '/$tenant/app/sales/crm'
    | '/$tenant/app/sales/invoices'
    | '/$tenant/app/sales/pipeline'
    | '/$tenant/app/sales/product-catalog'
    | '/$tenant/app/sales/promotions'
    | '/$tenant/app/sales/quotes'
    | '/$tenant/app/sales/subscriptions'
    | '/$tenant/app/support/knowledge'
    | '/$tenant/app/support/members'
    | '/$tenant/app/support/tickets'
    | '/$tenant/app/marketing/'
    | '/$tenant/app/sales/'
    | '/$tenant/app/support/'
    | '/$tenant/api/crm/contacts/$contactId'
    | '/$tenant/api/crm/customers/$customerId'
    | '/$tenant/api/invoices/$invoiceId/finalize'
    | '/$tenant/api/invoices/$invoiceId/pay'
    | '/$tenant/api/invoices/$invoiceId/pdf'
    | '/$tenant/api/members/$memberId/audit-logs'
    | '/$tenant/api/product-catalog/plans/$planId'
    | '/$tenant/api/quotes/$quoteId/accept'
    | '/$tenant/api/quotes/$quoteId/pdf'
    | '/$tenant/api/quotes/$quoteId/reject'
    | '/$tenant/api/quotes/$quoteId/send'
    | '/$tenant/api/support/organizations/$organizationId'
    | '/$tenant/api/tickets/$ticketId/audit-logs'
    | '/$tenant/app/sales/crm/$customerId'
    | '/$tenant/app/sales/crm/contacts'
    | '/$tenant/app/support/members/$memberId'
    | '/$tenant/app/support/organizations/$organizationId'
    | '/$tenant/app/sales/crm/'
    | '/$tenant/app/sales/promotions/'
    | '/$tenant/app/support/members/'
    | '/$tenant/api/crm/customers/$customerId/contacts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TenantRoute: typeof TenantRouteWithChildren
  DatabaseRoute: typeof DatabaseRoute
  FormsRoute: typeof FormsRouteWithChildren
  McpRoute: typeof McpRoute
  StoreRoute: typeof StoreRoute
  TableRoute: typeof TableRoute
  TodosRoute: typeof TodosRoute
  ApiTodosRoute: typeof ApiTodosRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiUserOrganizationsRoute: typeof ApiUserOrganizationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table': {
      id: '/table'
      path: '/table'
      fullPath: '/table'
      preLoaderRoute: typeof TableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms': {
      id: '/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof FormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/database': {
      id: '/database'
      path: '/database'
      fullPath: '/database'
      preLoaderRoute: typeof DatabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tenant': {
      id: '/$tenant'
      path: '/$tenant'
      fullPath: '/$tenant'
      preLoaderRoute: typeof TenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/simple': {
      id: '/forms/simple'
      path: '/simple'
      fullPath: '/forms/simple'
      preLoaderRoute: typeof FormsSimpleRouteImport
      parentRoute: typeof FormsRoute
    }
    '/forms/address': {
      id: '/forms/address'
      path: '/address'
      fullPath: '/forms/address'
      preLoaderRoute: typeof FormsAddressRouteImport
      parentRoute: typeof FormsRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/todos': {
      id: '/api/todos'
      path: '/api/todos'
      fullPath: '/api/todos'
      preLoaderRoute: typeof ApiTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tenant/app': {
      id: '/$tenant/app'
      path: '/app'
      fullPath: '/$tenant/app'
      preLoaderRoute: typeof TenantAppRouteImport
      parentRoute: typeof TenantRoute
    }
    '/api/user/organizations': {
      id: '/api/user/organizations'
      path: '/api/user/organizations'
      fullPath: '/api/user/organizations'
      preLoaderRoute: typeof ApiUserOrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tenant/app/support': {
      id: '/$tenant/app/support'
      path: '/support'
      fullPath: '/$tenant/app/support'
      preLoaderRoute: typeof TenantAppSupportRouteImport
      parentRoute: typeof TenantAppRoute
    }
    '/$tenant/app/sales': {
      id: '/$tenant/app/sales'
      path: '/sales'
      fullPath: '/$tenant/app/sales'
      preLoaderRoute: typeof TenantAppSalesRouteImport
      parentRoute: typeof TenantAppRoute
    }
    '/$tenant/app/marketing': {
      id: '/$tenant/app/marketing'
      path: '/marketing'
      fullPath: '/$tenant/app/marketing'
      preLoaderRoute: typeof TenantAppMarketingRouteImport
      parentRoute: typeof TenantAppRoute
    }
    '/$tenant/app/login': {
      id: '/$tenant/app/login'
      path: '/login'
      fullPath: '/$tenant/app/login'
      preLoaderRoute: typeof TenantAppLoginRouteImport
      parentRoute: typeof TenantAppRoute
    }
    '/$tenant/api/users': {
      id: '/$tenant/api/users'
      path: '/api/users'
      fullPath: '/$tenant/api/users'
      preLoaderRoute: typeof TenantApiUsersRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/api/tickets': {
      id: '/$tenant/api/tickets'
      path: '/api/tickets'
      fullPath: '/$tenant/api/tickets'
      preLoaderRoute: typeof TenantApiTicketsRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/api/subscriptions': {
      id: '/$tenant/api/subscriptions'
      path: '/api/subscriptions'
      fullPath: '/$tenant/api/subscriptions'
      preLoaderRoute: typeof TenantApiSubscriptionsRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/api/quotes': {
      id: '/$tenant/api/quotes'
      path: '/api/quotes'
      fullPath: '/$tenant/api/quotes'
      preLoaderRoute: typeof TenantApiQuotesRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/api/pipelines': {
      id: '/$tenant/api/pipelines'
      path: '/api/pipelines'
      fullPath: '/$tenant/api/pipelines'
      preLoaderRoute: typeof TenantApiPipelinesRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/api/membership': {
      id: '/$tenant/api/membership'
      path: '/api/membership'
      fullPath: '/$tenant/api/membership'
      preLoaderRoute: typeof TenantApiMembershipRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/api/members': {
      id: '/$tenant/api/members'
      path: '/api/members'
      fullPath: '/$tenant/api/members'
      preLoaderRoute: typeof TenantApiMembersRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/api/invoices': {
      id: '/$tenant/api/invoices'
      path: '/api/invoices'
      fullPath: '/$tenant/api/invoices'
      preLoaderRoute: typeof TenantApiInvoicesRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/api/deals': {
      id: '/$tenant/api/deals'
      path: '/api/deals'
      fullPath: '/$tenant/api/deals'
      preLoaderRoute: typeof TenantApiDealsRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/api/coupons': {
      id: '/$tenant/api/coupons'
      path: '/api/coupons'
      fullPath: '/$tenant/api/coupons'
      preLoaderRoute: typeof TenantApiCouponsRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/app/support/': {
      id: '/$tenant/app/support/'
      path: '/'
      fullPath: '/$tenant/app/support/'
      preLoaderRoute: typeof TenantAppSupportIndexRouteImport
      parentRoute: typeof TenantAppSupportRoute
    }
    '/$tenant/app/sales/': {
      id: '/$tenant/app/sales/'
      path: '/'
      fullPath: '/$tenant/app/sales/'
      preLoaderRoute: typeof TenantAppSalesIndexRouteImport
      parentRoute: typeof TenantAppSalesRoute
    }
    '/$tenant/app/marketing/': {
      id: '/$tenant/app/marketing/'
      path: '/'
      fullPath: '/$tenant/app/marketing/'
      preLoaderRoute: typeof TenantAppMarketingIndexRouteImport
      parentRoute: typeof TenantAppMarketingRoute
    }
    '/$tenant/app/support/tickets': {
      id: '/$tenant/app/support/tickets'
      path: '/tickets'
      fullPath: '/$tenant/app/support/tickets'
      preLoaderRoute: typeof TenantAppSupportTicketsRouteImport
      parentRoute: typeof TenantAppSupportRoute
    }
    '/$tenant/app/support/members': {
      id: '/$tenant/app/support/members'
      path: '/members'
      fullPath: '/$tenant/app/support/members'
      preLoaderRoute: typeof TenantAppSupportMembersRouteImport
      parentRoute: typeof TenantAppSupportRoute
    }
    '/$tenant/app/support/knowledge': {
      id: '/$tenant/app/support/knowledge'
      path: '/knowledge'
      fullPath: '/$tenant/app/support/knowledge'
      preLoaderRoute: typeof TenantAppSupportKnowledgeRouteImport
      parentRoute: typeof TenantAppSupportRoute
    }
    '/$tenant/app/sales/subscriptions': {
      id: '/$tenant/app/sales/subscriptions'
      path: '/subscriptions'
      fullPath: '/$tenant/app/sales/subscriptions'
      preLoaderRoute: typeof TenantAppSalesSubscriptionsRouteImport
      parentRoute: typeof TenantAppSalesRoute
    }
    '/$tenant/app/sales/quotes': {
      id: '/$tenant/app/sales/quotes'
      path: '/quotes'
      fullPath: '/$tenant/app/sales/quotes'
      preLoaderRoute: typeof TenantAppSalesQuotesRouteImport
      parentRoute: typeof TenantAppSalesRoute
    }
    '/$tenant/app/sales/promotions': {
      id: '/$tenant/app/sales/promotions'
      path: '/promotions'
      fullPath: '/$tenant/app/sales/promotions'
      preLoaderRoute: typeof TenantAppSalesPromotionsRouteImport
      parentRoute: typeof TenantAppSalesRoute
    }
    '/$tenant/app/sales/product-catalog': {
      id: '/$tenant/app/sales/product-catalog'
      path: '/product-catalog'
      fullPath: '/$tenant/app/sales/product-catalog'
      preLoaderRoute: typeof TenantAppSalesProductCatalogRouteImport
      parentRoute: typeof TenantAppSalesRoute
    }
    '/$tenant/app/sales/pipeline': {
      id: '/$tenant/app/sales/pipeline'
      path: '/pipeline'
      fullPath: '/$tenant/app/sales/pipeline'
      preLoaderRoute: typeof TenantAppSalesPipelineRouteImport
      parentRoute: typeof TenantAppSalesRoute
    }
    '/$tenant/app/sales/invoices': {
      id: '/$tenant/app/sales/invoices'
      path: '/invoices'
      fullPath: '/$tenant/app/sales/invoices'
      preLoaderRoute: typeof TenantAppSalesInvoicesRouteImport
      parentRoute: typeof TenantAppSalesRoute
    }
    '/$tenant/app/sales/crm': {
      id: '/$tenant/app/sales/crm'
      path: '/crm'
      fullPath: '/$tenant/app/sales/crm'
      preLoaderRoute: typeof TenantAppSalesCrmRouteImport
      parentRoute: typeof TenantAppSalesRoute
    }
    '/$tenant/app/sales/add-ons': {
      id: '/$tenant/app/sales/add-ons'
      path: '/add-ons'
      fullPath: '/$tenant/app/sales/add-ons'
      preLoaderRoute: typeof TenantAppSalesAddOnsRouteImport
      parentRoute: typeof TenantAppSalesRoute
    }
    '/$tenant/app/marketing/social': {
      id: '/$tenant/app/marketing/social'
      path: '/social'
      fullPath: '/$tenant/app/marketing/social'
      preLoaderRoute: typeof TenantAppMarketingSocialRouteImport
      parentRoute: typeof TenantAppMarketingRoute
    }
    '/$tenant/app/marketing/journeys': {
      id: '/$tenant/app/marketing/journeys'
      path: '/journeys'
      fullPath: '/$tenant/app/marketing/journeys'
      preLoaderRoute: typeof TenantAppMarketingJourneysRouteImport
      parentRoute: typeof TenantAppMarketingRoute
    }
    '/$tenant/app/marketing/content': {
      id: '/$tenant/app/marketing/content'
      path: '/content'
      fullPath: '/$tenant/app/marketing/content'
      preLoaderRoute: typeof TenantAppMarketingContentRouteImport
      parentRoute: typeof TenantAppMarketingRoute
    }
    '/$tenant/app/marketing/campaigns': {
      id: '/$tenant/app/marketing/campaigns'
      path: '/campaigns'
      fullPath: '/$tenant/app/marketing/campaigns'
      preLoaderRoute: typeof TenantAppMarketingCampaignsRouteImport
      parentRoute: typeof TenantAppMarketingRoute
    }
    '/$tenant/app/marketing/audiences': {
      id: '/$tenant/app/marketing/audiences'
      path: '/audiences'
      fullPath: '/$tenant/app/marketing/audiences'
      preLoaderRoute: typeof TenantAppMarketingAudiencesRouteImport
      parentRoute: typeof TenantAppMarketingRoute
    }
    '/$tenant/app/marketing/affiliates': {
      id: '/$tenant/app/marketing/affiliates'
      path: '/affiliates'
      fullPath: '/$tenant/app/marketing/affiliates'
      preLoaderRoute: typeof TenantAppMarketingAffiliatesRouteImport
      parentRoute: typeof TenantAppMarketingRoute
    }
    '/$tenant/api/tickets/$ticketId': {
      id: '/$tenant/api/tickets/$ticketId'
      path: '/$ticketId'
      fullPath: '/$tenant/api/tickets/$ticketId'
      preLoaderRoute: typeof TenantApiTicketsTicketIdRouteImport
      parentRoute: typeof TenantApiTicketsRoute
    }
    '/$tenant/api/subscriptions/$subscriptionId': {
      id: '/$tenant/api/subscriptions/$subscriptionId'
      path: '/$subscriptionId'
      fullPath: '/$tenant/api/subscriptions/$subscriptionId'
      preLoaderRoute: typeof TenantApiSubscriptionsSubscriptionIdRouteImport
      parentRoute: typeof TenantApiSubscriptionsRoute
    }
    '/$tenant/api/settings/api-keys': {
      id: '/$tenant/api/settings/api-keys'
      path: '/api/settings/api-keys'
      fullPath: '/$tenant/api/settings/api-keys'
      preLoaderRoute: typeof TenantApiSettingsApiKeysRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/api/quotes/$quoteId': {
      id: '/$tenant/api/quotes/$quoteId'
      path: '/$quoteId'
      fullPath: '/$tenant/api/quotes/$quoteId'
      preLoaderRoute: typeof TenantApiQuotesQuoteIdRouteImport
      parentRoute: typeof TenantApiQuotesRoute
    }
    '/$tenant/api/product-catalog/products': {
      id: '/$tenant/api/product-catalog/products'
      path: '/api/product-catalog/products'
      fullPath: '/$tenant/api/product-catalog/products'
      preLoaderRoute: typeof TenantApiProductCatalogProductsRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/api/product-catalog/plans': {
      id: '/$tenant/api/product-catalog/plans'
      path: '/api/product-catalog/plans'
      fullPath: '/$tenant/api/product-catalog/plans'
      preLoaderRoute: typeof TenantApiProductCatalogPlansRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/api/product-catalog/add-ons': {
      id: '/$tenant/api/product-catalog/add-ons'
      path: '/api/product-catalog/add-ons'
      fullPath: '/$tenant/api/product-catalog/add-ons'
      preLoaderRoute: typeof TenantApiProductCatalogAddOnsRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/api/members/$memberId': {
      id: '/$tenant/api/members/$memberId'
      path: '/$memberId'
      fullPath: '/$tenant/api/members/$memberId'
      preLoaderRoute: typeof TenantApiMembersMemberIdRouteImport
      parentRoute: typeof TenantApiMembersRoute
    }
    '/$tenant/api/knowledge/search': {
      id: '/$tenant/api/knowledge/search'
      path: '/api/knowledge/search'
      fullPath: '/$tenant/api/knowledge/search'
      preLoaderRoute: typeof TenantApiKnowledgeSearchRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/api/knowledge/playbooks': {
      id: '/$tenant/api/knowledge/playbooks'
      path: '/api/knowledge/playbooks'
      fullPath: '/$tenant/api/knowledge/playbooks'
      preLoaderRoute: typeof TenantApiKnowledgePlaybooksRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/api/knowledge/articles': {
      id: '/$tenant/api/knowledge/articles'
      path: '/api/knowledge/articles'
      fullPath: '/$tenant/api/knowledge/articles'
      preLoaderRoute: typeof TenantApiKnowledgeArticlesRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/api/invoices/$invoiceId': {
      id: '/$tenant/api/invoices/$invoiceId'
      path: '/$invoiceId'
      fullPath: '/$tenant/api/invoices/$invoiceId'
      preLoaderRoute: typeof TenantApiInvoicesInvoiceIdRouteImport
      parentRoute: typeof TenantApiInvoicesRoute
    }
    '/$tenant/api/deals/$dealId': {
      id: '/$tenant/api/deals/$dealId'
      path: '/$dealId'
      fullPath: '/$tenant/api/deals/$dealId'
      preLoaderRoute: typeof TenantApiDealsDealIdRouteImport
      parentRoute: typeof TenantApiDealsRoute
    }
    '/$tenant/api/crm/customers': {
      id: '/$tenant/api/crm/customers'
      path: '/api/crm/customers'
      fullPath: '/$tenant/api/crm/customers'
      preLoaderRoute: typeof TenantApiCrmCustomersRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/api/crm/contacts': {
      id: '/$tenant/api/crm/contacts'
      path: '/api/crm/contacts'
      fullPath: '/$tenant/api/crm/contacts'
      preLoaderRoute: typeof TenantApiCrmContactsRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/api/coupons/validate': {
      id: '/$tenant/api/coupons/validate'
      path: '/validate'
      fullPath: '/$tenant/api/coupons/validate'
      preLoaderRoute: typeof TenantApiCouponsValidateRouteImport
      parentRoute: typeof TenantApiCouponsRoute
    }
    '/$tenant/api/coupons/$couponId': {
      id: '/$tenant/api/coupons/$couponId'
      path: '/$couponId'
      fullPath: '/$tenant/api/coupons/$couponId'
      preLoaderRoute: typeof TenantApiCouponsCouponIdRouteImport
      parentRoute: typeof TenantApiCouponsRoute
    }
    '/$tenant/app/support/members/': {
      id: '/$tenant/app/support/members/'
      path: '/'
      fullPath: '/$tenant/app/support/members/'
      preLoaderRoute: typeof TenantAppSupportMembersIndexRouteImport
      parentRoute: typeof TenantAppSupportMembersRoute
    }
    '/$tenant/app/sales/promotions/': {
      id: '/$tenant/app/sales/promotions/'
      path: '/'
      fullPath: '/$tenant/app/sales/promotions/'
      preLoaderRoute: typeof TenantAppSalesPromotionsIndexRouteImport
      parentRoute: typeof TenantAppSalesPromotionsRoute
    }
    '/$tenant/app/sales/crm/': {
      id: '/$tenant/app/sales/crm/'
      path: '/'
      fullPath: '/$tenant/app/sales/crm/'
      preLoaderRoute: typeof TenantAppSalesCrmIndexRouteImport
      parentRoute: typeof TenantAppSalesCrmRoute
    }
    '/$tenant/app/support/organizations/$organizationId': {
      id: '/$tenant/app/support/organizations/$organizationId'
      path: '/organizations/$organizationId'
      fullPath: '/$tenant/app/support/organizations/$organizationId'
      preLoaderRoute: typeof TenantAppSupportOrganizationsOrganizationIdRouteImport
      parentRoute: typeof TenantAppSupportRoute
    }
    '/$tenant/app/support/members/$memberId': {
      id: '/$tenant/app/support/members/$memberId'
      path: '/$memberId'
      fullPath: '/$tenant/app/support/members/$memberId'
      preLoaderRoute: typeof TenantAppSupportMembersMemberIdRouteImport
      parentRoute: typeof TenantAppSupportMembersRoute
    }
    '/$tenant/app/sales/crm/contacts': {
      id: '/$tenant/app/sales/crm/contacts'
      path: '/contacts'
      fullPath: '/$tenant/app/sales/crm/contacts'
      preLoaderRoute: typeof TenantAppSalesCrmContactsRouteImport
      parentRoute: typeof TenantAppSalesCrmRoute
    }
    '/$tenant/app/sales/crm/$customerId': {
      id: '/$tenant/app/sales/crm/$customerId'
      path: '/$customerId'
      fullPath: '/$tenant/app/sales/crm/$customerId'
      preLoaderRoute: typeof TenantAppSalesCrmCustomerIdRouteImport
      parentRoute: typeof TenantAppSalesCrmRoute
    }
    '/$tenant/api/tickets/$ticketId/audit-logs': {
      id: '/$tenant/api/tickets/$ticketId/audit-logs'
      path: '/audit-logs'
      fullPath: '/$tenant/api/tickets/$ticketId/audit-logs'
      preLoaderRoute: typeof TenantApiTicketsTicketIdAuditLogsRouteImport
      parentRoute: typeof TenantApiTicketsTicketIdRoute
    }
    '/$tenant/api/support/organizations/$organizationId': {
      id: '/$tenant/api/support/organizations/$organizationId'
      path: '/api/support/organizations/$organizationId'
      fullPath: '/$tenant/api/support/organizations/$organizationId'
      preLoaderRoute: typeof TenantApiSupportOrganizationsOrganizationIdRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/api/quotes/$quoteId/send': {
      id: '/$tenant/api/quotes/$quoteId/send'
      path: '/send'
      fullPath: '/$tenant/api/quotes/$quoteId/send'
      preLoaderRoute: typeof TenantApiQuotesQuoteIdSendRouteImport
      parentRoute: typeof TenantApiQuotesQuoteIdRoute
    }
    '/$tenant/api/quotes/$quoteId/reject': {
      id: '/$tenant/api/quotes/$quoteId/reject'
      path: '/reject'
      fullPath: '/$tenant/api/quotes/$quoteId/reject'
      preLoaderRoute: typeof TenantApiQuotesQuoteIdRejectRouteImport
      parentRoute: typeof TenantApiQuotesQuoteIdRoute
    }
    '/$tenant/api/quotes/$quoteId/pdf': {
      id: '/$tenant/api/quotes/$quoteId/pdf'
      path: '/pdf'
      fullPath: '/$tenant/api/quotes/$quoteId/pdf'
      preLoaderRoute: typeof TenantApiQuotesQuoteIdPdfRouteImport
      parentRoute: typeof TenantApiQuotesQuoteIdRoute
    }
    '/$tenant/api/quotes/$quoteId/accept': {
      id: '/$tenant/api/quotes/$quoteId/accept'
      path: '/accept'
      fullPath: '/$tenant/api/quotes/$quoteId/accept'
      preLoaderRoute: typeof TenantApiQuotesQuoteIdAcceptRouteImport
      parentRoute: typeof TenantApiQuotesQuoteIdRoute
    }
    '/$tenant/api/product-catalog/plans/$planId': {
      id: '/$tenant/api/product-catalog/plans/$planId'
      path: '/$planId'
      fullPath: '/$tenant/api/product-catalog/plans/$planId'
      preLoaderRoute: typeof TenantApiProductCatalogPlansPlanIdRouteImport
      parentRoute: typeof TenantApiProductCatalogPlansRoute
    }
    '/$tenant/api/members/$memberId/audit-logs': {
      id: '/$tenant/api/members/$memberId/audit-logs'
      path: '/audit-logs'
      fullPath: '/$tenant/api/members/$memberId/audit-logs'
      preLoaderRoute: typeof TenantApiMembersMemberIdAuditLogsRouteImport
      parentRoute: typeof TenantApiMembersMemberIdRoute
    }
    '/$tenant/api/invoices/$invoiceId/pdf': {
      id: '/$tenant/api/invoices/$invoiceId/pdf'
      path: '/pdf'
      fullPath: '/$tenant/api/invoices/$invoiceId/pdf'
      preLoaderRoute: typeof TenantApiInvoicesInvoiceIdPdfRouteImport
      parentRoute: typeof TenantApiInvoicesInvoiceIdRoute
    }
    '/$tenant/api/invoices/$invoiceId/pay': {
      id: '/$tenant/api/invoices/$invoiceId/pay'
      path: '/pay'
      fullPath: '/$tenant/api/invoices/$invoiceId/pay'
      preLoaderRoute: typeof TenantApiInvoicesInvoiceIdPayRouteImport
      parentRoute: typeof TenantApiInvoicesInvoiceIdRoute
    }
    '/$tenant/api/invoices/$invoiceId/finalize': {
      id: '/$tenant/api/invoices/$invoiceId/finalize'
      path: '/finalize'
      fullPath: '/$tenant/api/invoices/$invoiceId/finalize'
      preLoaderRoute: typeof TenantApiInvoicesInvoiceIdFinalizeRouteImport
      parentRoute: typeof TenantApiInvoicesInvoiceIdRoute
    }
    '/$tenant/api/crm/customers/$customerId': {
      id: '/$tenant/api/crm/customers/$customerId'
      path: '/$customerId'
      fullPath: '/$tenant/api/crm/customers/$customerId'
      preLoaderRoute: typeof TenantApiCrmCustomersCustomerIdRouteImport
      parentRoute: typeof TenantApiCrmCustomersRoute
    }
    '/$tenant/api/crm/contacts/$contactId': {
      id: '/$tenant/api/crm/contacts/$contactId'
      path: '/$contactId'
      fullPath: '/$tenant/api/crm/contacts/$contactId'
      preLoaderRoute: typeof TenantApiCrmContactsContactIdRouteImport
      parentRoute: typeof TenantApiCrmContactsRoute
    }
    '/$tenant/api/crm/customers/$customerId/contacts': {
      id: '/$tenant/api/crm/customers/$customerId/contacts'
      path: '/contacts'
      fullPath: '/$tenant/api/crm/customers/$customerId/contacts'
      preLoaderRoute: typeof TenantApiCrmCustomersCustomerIdContactsRouteImport
      parentRoute: typeof TenantApiCrmCustomersCustomerIdRoute
    }
  }
}

interface TenantAppMarketingRouteChildren {
  TenantAppMarketingAffiliatesRoute: typeof TenantAppMarketingAffiliatesRoute
  TenantAppMarketingAudiencesRoute: typeof TenantAppMarketingAudiencesRoute
  TenantAppMarketingCampaignsRoute: typeof TenantAppMarketingCampaignsRoute
  TenantAppMarketingContentRoute: typeof TenantAppMarketingContentRoute
  TenantAppMarketingJourneysRoute: typeof TenantAppMarketingJourneysRoute
  TenantAppMarketingSocialRoute: typeof TenantAppMarketingSocialRoute
  TenantAppMarketingIndexRoute: typeof TenantAppMarketingIndexRoute
}

const TenantAppMarketingRouteChildren: TenantAppMarketingRouteChildren = {
  TenantAppMarketingAffiliatesRoute: TenantAppMarketingAffiliatesRoute,
  TenantAppMarketingAudiencesRoute: TenantAppMarketingAudiencesRoute,
  TenantAppMarketingCampaignsRoute: TenantAppMarketingCampaignsRoute,
  TenantAppMarketingContentRoute: TenantAppMarketingContentRoute,
  TenantAppMarketingJourneysRoute: TenantAppMarketingJourneysRoute,
  TenantAppMarketingSocialRoute: TenantAppMarketingSocialRoute,
  TenantAppMarketingIndexRoute: TenantAppMarketingIndexRoute,
}

const TenantAppMarketingRouteWithChildren =
  TenantAppMarketingRoute._addFileChildren(TenantAppMarketingRouteChildren)

interface TenantAppSalesCrmRouteChildren {
  TenantAppSalesCrmCustomerIdRoute: typeof TenantAppSalesCrmCustomerIdRoute
  TenantAppSalesCrmContactsRoute: typeof TenantAppSalesCrmContactsRoute
  TenantAppSalesCrmIndexRoute: typeof TenantAppSalesCrmIndexRoute
}

const TenantAppSalesCrmRouteChildren: TenantAppSalesCrmRouteChildren = {
  TenantAppSalesCrmCustomerIdRoute: TenantAppSalesCrmCustomerIdRoute,
  TenantAppSalesCrmContactsRoute: TenantAppSalesCrmContactsRoute,
  TenantAppSalesCrmIndexRoute: TenantAppSalesCrmIndexRoute,
}

const TenantAppSalesCrmRouteWithChildren =
  TenantAppSalesCrmRoute._addFileChildren(TenantAppSalesCrmRouteChildren)

interface TenantAppSalesPromotionsRouteChildren {
  TenantAppSalesPromotionsIndexRoute: typeof TenantAppSalesPromotionsIndexRoute
}

const TenantAppSalesPromotionsRouteChildren: TenantAppSalesPromotionsRouteChildren =
  {
    TenantAppSalesPromotionsIndexRoute: TenantAppSalesPromotionsIndexRoute,
  }

const TenantAppSalesPromotionsRouteWithChildren =
  TenantAppSalesPromotionsRoute._addFileChildren(
    TenantAppSalesPromotionsRouteChildren,
  )

interface TenantAppSalesRouteChildren {
  TenantAppSalesAddOnsRoute: typeof TenantAppSalesAddOnsRoute
  TenantAppSalesCrmRoute: typeof TenantAppSalesCrmRouteWithChildren
  TenantAppSalesInvoicesRoute: typeof TenantAppSalesInvoicesRoute
  TenantAppSalesPipelineRoute: typeof TenantAppSalesPipelineRoute
  TenantAppSalesProductCatalogRoute: typeof TenantAppSalesProductCatalogRoute
  TenantAppSalesPromotionsRoute: typeof TenantAppSalesPromotionsRouteWithChildren
  TenantAppSalesQuotesRoute: typeof TenantAppSalesQuotesRoute
  TenantAppSalesSubscriptionsRoute: typeof TenantAppSalesSubscriptionsRoute
  TenantAppSalesIndexRoute: typeof TenantAppSalesIndexRoute
}

const TenantAppSalesRouteChildren: TenantAppSalesRouteChildren = {
  TenantAppSalesAddOnsRoute: TenantAppSalesAddOnsRoute,
  TenantAppSalesCrmRoute: TenantAppSalesCrmRouteWithChildren,
  TenantAppSalesInvoicesRoute: TenantAppSalesInvoicesRoute,
  TenantAppSalesPipelineRoute: TenantAppSalesPipelineRoute,
  TenantAppSalesProductCatalogRoute: TenantAppSalesProductCatalogRoute,
  TenantAppSalesPromotionsRoute: TenantAppSalesPromotionsRouteWithChildren,
  TenantAppSalesQuotesRoute: TenantAppSalesQuotesRoute,
  TenantAppSalesSubscriptionsRoute: TenantAppSalesSubscriptionsRoute,
  TenantAppSalesIndexRoute: TenantAppSalesIndexRoute,
}

const TenantAppSalesRouteWithChildren = TenantAppSalesRoute._addFileChildren(
  TenantAppSalesRouteChildren,
)

interface TenantAppSupportMembersRouteChildren {
  TenantAppSupportMembersMemberIdRoute: typeof TenantAppSupportMembersMemberIdRoute
  TenantAppSupportMembersIndexRoute: typeof TenantAppSupportMembersIndexRoute
}

const TenantAppSupportMembersRouteChildren: TenantAppSupportMembersRouteChildren =
  {
    TenantAppSupportMembersMemberIdRoute: TenantAppSupportMembersMemberIdRoute,
    TenantAppSupportMembersIndexRoute: TenantAppSupportMembersIndexRoute,
  }

const TenantAppSupportMembersRouteWithChildren =
  TenantAppSupportMembersRoute._addFileChildren(
    TenantAppSupportMembersRouteChildren,
  )

interface TenantAppSupportRouteChildren {
  TenantAppSupportKnowledgeRoute: typeof TenantAppSupportKnowledgeRoute
  TenantAppSupportMembersRoute: typeof TenantAppSupportMembersRouteWithChildren
  TenantAppSupportTicketsRoute: typeof TenantAppSupportTicketsRoute
  TenantAppSupportIndexRoute: typeof TenantAppSupportIndexRoute
  TenantAppSupportOrganizationsOrganizationIdRoute: typeof TenantAppSupportOrganizationsOrganizationIdRoute
}

const TenantAppSupportRouteChildren: TenantAppSupportRouteChildren = {
  TenantAppSupportKnowledgeRoute: TenantAppSupportKnowledgeRoute,
  TenantAppSupportMembersRoute: TenantAppSupportMembersRouteWithChildren,
  TenantAppSupportTicketsRoute: TenantAppSupportTicketsRoute,
  TenantAppSupportIndexRoute: TenantAppSupportIndexRoute,
  TenantAppSupportOrganizationsOrganizationIdRoute:
    TenantAppSupportOrganizationsOrganizationIdRoute,
}

const TenantAppSupportRouteWithChildren =
  TenantAppSupportRoute._addFileChildren(TenantAppSupportRouteChildren)

interface TenantAppRouteChildren {
  TenantAppLoginRoute: typeof TenantAppLoginRoute
  TenantAppMarketingRoute: typeof TenantAppMarketingRouteWithChildren
  TenantAppSalesRoute: typeof TenantAppSalesRouteWithChildren
  TenantAppSupportRoute: typeof TenantAppSupportRouteWithChildren
}

const TenantAppRouteChildren: TenantAppRouteChildren = {
  TenantAppLoginRoute: TenantAppLoginRoute,
  TenantAppMarketingRoute: TenantAppMarketingRouteWithChildren,
  TenantAppSalesRoute: TenantAppSalesRouteWithChildren,
  TenantAppSupportRoute: TenantAppSupportRouteWithChildren,
}

const TenantAppRouteWithChildren = TenantAppRoute._addFileChildren(
  TenantAppRouteChildren,
)

interface TenantApiCouponsRouteChildren {
  TenantApiCouponsCouponIdRoute: typeof TenantApiCouponsCouponIdRoute
  TenantApiCouponsValidateRoute: typeof TenantApiCouponsValidateRoute
}

const TenantApiCouponsRouteChildren: TenantApiCouponsRouteChildren = {
  TenantApiCouponsCouponIdRoute: TenantApiCouponsCouponIdRoute,
  TenantApiCouponsValidateRoute: TenantApiCouponsValidateRoute,
}

const TenantApiCouponsRouteWithChildren =
  TenantApiCouponsRoute._addFileChildren(TenantApiCouponsRouteChildren)

interface TenantApiDealsRouteChildren {
  TenantApiDealsDealIdRoute: typeof TenantApiDealsDealIdRoute
}

const TenantApiDealsRouteChildren: TenantApiDealsRouteChildren = {
  TenantApiDealsDealIdRoute: TenantApiDealsDealIdRoute,
}

const TenantApiDealsRouteWithChildren = TenantApiDealsRoute._addFileChildren(
  TenantApiDealsRouteChildren,
)

interface TenantApiInvoicesInvoiceIdRouteChildren {
  TenantApiInvoicesInvoiceIdFinalizeRoute: typeof TenantApiInvoicesInvoiceIdFinalizeRoute
  TenantApiInvoicesInvoiceIdPayRoute: typeof TenantApiInvoicesInvoiceIdPayRoute
  TenantApiInvoicesInvoiceIdPdfRoute: typeof TenantApiInvoicesInvoiceIdPdfRoute
}

const TenantApiInvoicesInvoiceIdRouteChildren: TenantApiInvoicesInvoiceIdRouteChildren =
  {
    TenantApiInvoicesInvoiceIdFinalizeRoute:
      TenantApiInvoicesInvoiceIdFinalizeRoute,
    TenantApiInvoicesInvoiceIdPayRoute: TenantApiInvoicesInvoiceIdPayRoute,
    TenantApiInvoicesInvoiceIdPdfRoute: TenantApiInvoicesInvoiceIdPdfRoute,
  }

const TenantApiInvoicesInvoiceIdRouteWithChildren =
  TenantApiInvoicesInvoiceIdRoute._addFileChildren(
    TenantApiInvoicesInvoiceIdRouteChildren,
  )

interface TenantApiInvoicesRouteChildren {
  TenantApiInvoicesInvoiceIdRoute: typeof TenantApiInvoicesInvoiceIdRouteWithChildren
}

const TenantApiInvoicesRouteChildren: TenantApiInvoicesRouteChildren = {
  TenantApiInvoicesInvoiceIdRoute: TenantApiInvoicesInvoiceIdRouteWithChildren,
}

const TenantApiInvoicesRouteWithChildren =
  TenantApiInvoicesRoute._addFileChildren(TenantApiInvoicesRouteChildren)

interface TenantApiMembersMemberIdRouteChildren {
  TenantApiMembersMemberIdAuditLogsRoute: typeof TenantApiMembersMemberIdAuditLogsRoute
}

const TenantApiMembersMemberIdRouteChildren: TenantApiMembersMemberIdRouteChildren =
  {
    TenantApiMembersMemberIdAuditLogsRoute:
      TenantApiMembersMemberIdAuditLogsRoute,
  }

const TenantApiMembersMemberIdRouteWithChildren =
  TenantApiMembersMemberIdRoute._addFileChildren(
    TenantApiMembersMemberIdRouteChildren,
  )

interface TenantApiMembersRouteChildren {
  TenantApiMembersMemberIdRoute: typeof TenantApiMembersMemberIdRouteWithChildren
}

const TenantApiMembersRouteChildren: TenantApiMembersRouteChildren = {
  TenantApiMembersMemberIdRoute: TenantApiMembersMemberIdRouteWithChildren,
}

const TenantApiMembersRouteWithChildren =
  TenantApiMembersRoute._addFileChildren(TenantApiMembersRouteChildren)

interface TenantApiQuotesQuoteIdRouteChildren {
  TenantApiQuotesQuoteIdAcceptRoute: typeof TenantApiQuotesQuoteIdAcceptRoute
  TenantApiQuotesQuoteIdPdfRoute: typeof TenantApiQuotesQuoteIdPdfRoute
  TenantApiQuotesQuoteIdRejectRoute: typeof TenantApiQuotesQuoteIdRejectRoute
  TenantApiQuotesQuoteIdSendRoute: typeof TenantApiQuotesQuoteIdSendRoute
}

const TenantApiQuotesQuoteIdRouteChildren: TenantApiQuotesQuoteIdRouteChildren =
  {
    TenantApiQuotesQuoteIdAcceptRoute: TenantApiQuotesQuoteIdAcceptRoute,
    TenantApiQuotesQuoteIdPdfRoute: TenantApiQuotesQuoteIdPdfRoute,
    TenantApiQuotesQuoteIdRejectRoute: TenantApiQuotesQuoteIdRejectRoute,
    TenantApiQuotesQuoteIdSendRoute: TenantApiQuotesQuoteIdSendRoute,
  }

const TenantApiQuotesQuoteIdRouteWithChildren =
  TenantApiQuotesQuoteIdRoute._addFileChildren(
    TenantApiQuotesQuoteIdRouteChildren,
  )

interface TenantApiQuotesRouteChildren {
  TenantApiQuotesQuoteIdRoute: typeof TenantApiQuotesQuoteIdRouteWithChildren
}

const TenantApiQuotesRouteChildren: TenantApiQuotesRouteChildren = {
  TenantApiQuotesQuoteIdRoute: TenantApiQuotesQuoteIdRouteWithChildren,
}

const TenantApiQuotesRouteWithChildren = TenantApiQuotesRoute._addFileChildren(
  TenantApiQuotesRouteChildren,
)

interface TenantApiSubscriptionsRouteChildren {
  TenantApiSubscriptionsSubscriptionIdRoute: typeof TenantApiSubscriptionsSubscriptionIdRoute
}

const TenantApiSubscriptionsRouteChildren: TenantApiSubscriptionsRouteChildren =
  {
    TenantApiSubscriptionsSubscriptionIdRoute:
      TenantApiSubscriptionsSubscriptionIdRoute,
  }

const TenantApiSubscriptionsRouteWithChildren =
  TenantApiSubscriptionsRoute._addFileChildren(
    TenantApiSubscriptionsRouteChildren,
  )

interface TenantApiTicketsTicketIdRouteChildren {
  TenantApiTicketsTicketIdAuditLogsRoute: typeof TenantApiTicketsTicketIdAuditLogsRoute
}

const TenantApiTicketsTicketIdRouteChildren: TenantApiTicketsTicketIdRouteChildren =
  {
    TenantApiTicketsTicketIdAuditLogsRoute:
      TenantApiTicketsTicketIdAuditLogsRoute,
  }

const TenantApiTicketsTicketIdRouteWithChildren =
  TenantApiTicketsTicketIdRoute._addFileChildren(
    TenantApiTicketsTicketIdRouteChildren,
  )

interface TenantApiTicketsRouteChildren {
  TenantApiTicketsTicketIdRoute: typeof TenantApiTicketsTicketIdRouteWithChildren
}

const TenantApiTicketsRouteChildren: TenantApiTicketsRouteChildren = {
  TenantApiTicketsTicketIdRoute: TenantApiTicketsTicketIdRouteWithChildren,
}

const TenantApiTicketsRouteWithChildren =
  TenantApiTicketsRoute._addFileChildren(TenantApiTicketsRouteChildren)

interface TenantApiCrmContactsRouteChildren {
  TenantApiCrmContactsContactIdRoute: typeof TenantApiCrmContactsContactIdRoute
}

const TenantApiCrmContactsRouteChildren: TenantApiCrmContactsRouteChildren = {
  TenantApiCrmContactsContactIdRoute: TenantApiCrmContactsContactIdRoute,
}

const TenantApiCrmContactsRouteWithChildren =
  TenantApiCrmContactsRoute._addFileChildren(TenantApiCrmContactsRouteChildren)

interface TenantApiCrmCustomersCustomerIdRouteChildren {
  TenantApiCrmCustomersCustomerIdContactsRoute: typeof TenantApiCrmCustomersCustomerIdContactsRoute
}

const TenantApiCrmCustomersCustomerIdRouteChildren: TenantApiCrmCustomersCustomerIdRouteChildren =
  {
    TenantApiCrmCustomersCustomerIdContactsRoute:
      TenantApiCrmCustomersCustomerIdContactsRoute,
  }

const TenantApiCrmCustomersCustomerIdRouteWithChildren =
  TenantApiCrmCustomersCustomerIdRoute._addFileChildren(
    TenantApiCrmCustomersCustomerIdRouteChildren,
  )

interface TenantApiCrmCustomersRouteChildren {
  TenantApiCrmCustomersCustomerIdRoute: typeof TenantApiCrmCustomersCustomerIdRouteWithChildren
}

const TenantApiCrmCustomersRouteChildren: TenantApiCrmCustomersRouteChildren = {
  TenantApiCrmCustomersCustomerIdRoute:
    TenantApiCrmCustomersCustomerIdRouteWithChildren,
}

const TenantApiCrmCustomersRouteWithChildren =
  TenantApiCrmCustomersRoute._addFileChildren(
    TenantApiCrmCustomersRouteChildren,
  )

interface TenantApiProductCatalogPlansRouteChildren {
  TenantApiProductCatalogPlansPlanIdRoute: typeof TenantApiProductCatalogPlansPlanIdRoute
}

const TenantApiProductCatalogPlansRouteChildren: TenantApiProductCatalogPlansRouteChildren =
  {
    TenantApiProductCatalogPlansPlanIdRoute:
      TenantApiProductCatalogPlansPlanIdRoute,
  }

const TenantApiProductCatalogPlansRouteWithChildren =
  TenantApiProductCatalogPlansRoute._addFileChildren(
    TenantApiProductCatalogPlansRouteChildren,
  )

interface TenantRouteChildren {
  TenantAppRoute: typeof TenantAppRouteWithChildren
  TenantApiCouponsRoute: typeof TenantApiCouponsRouteWithChildren
  TenantApiDealsRoute: typeof TenantApiDealsRouteWithChildren
  TenantApiInvoicesRoute: typeof TenantApiInvoicesRouteWithChildren
  TenantApiMembersRoute: typeof TenantApiMembersRouteWithChildren
  TenantApiMembershipRoute: typeof TenantApiMembershipRoute
  TenantApiPipelinesRoute: typeof TenantApiPipelinesRoute
  TenantApiQuotesRoute: typeof TenantApiQuotesRouteWithChildren
  TenantApiSubscriptionsRoute: typeof TenantApiSubscriptionsRouteWithChildren
  TenantApiTicketsRoute: typeof TenantApiTicketsRouteWithChildren
  TenantApiUsersRoute: typeof TenantApiUsersRoute
  TenantApiCrmContactsRoute: typeof TenantApiCrmContactsRouteWithChildren
  TenantApiCrmCustomersRoute: typeof TenantApiCrmCustomersRouteWithChildren
  TenantApiKnowledgeArticlesRoute: typeof TenantApiKnowledgeArticlesRoute
  TenantApiKnowledgePlaybooksRoute: typeof TenantApiKnowledgePlaybooksRoute
  TenantApiKnowledgeSearchRoute: typeof TenantApiKnowledgeSearchRoute
  TenantApiProductCatalogAddOnsRoute: typeof TenantApiProductCatalogAddOnsRoute
  TenantApiProductCatalogPlansRoute: typeof TenantApiProductCatalogPlansRouteWithChildren
  TenantApiProductCatalogProductsRoute: typeof TenantApiProductCatalogProductsRoute
  TenantApiSettingsApiKeysRoute: typeof TenantApiSettingsApiKeysRoute
  TenantApiSupportOrganizationsOrganizationIdRoute: typeof TenantApiSupportOrganizationsOrganizationIdRoute
}

const TenantRouteChildren: TenantRouteChildren = {
  TenantAppRoute: TenantAppRouteWithChildren,
  TenantApiCouponsRoute: TenantApiCouponsRouteWithChildren,
  TenantApiDealsRoute: TenantApiDealsRouteWithChildren,
  TenantApiInvoicesRoute: TenantApiInvoicesRouteWithChildren,
  TenantApiMembersRoute: TenantApiMembersRouteWithChildren,
  TenantApiMembershipRoute: TenantApiMembershipRoute,
  TenantApiPipelinesRoute: TenantApiPipelinesRoute,
  TenantApiQuotesRoute: TenantApiQuotesRouteWithChildren,
  TenantApiSubscriptionsRoute: TenantApiSubscriptionsRouteWithChildren,
  TenantApiTicketsRoute: TenantApiTicketsRouteWithChildren,
  TenantApiUsersRoute: TenantApiUsersRoute,
  TenantApiCrmContactsRoute: TenantApiCrmContactsRouteWithChildren,
  TenantApiCrmCustomersRoute: TenantApiCrmCustomersRouteWithChildren,
  TenantApiKnowledgeArticlesRoute: TenantApiKnowledgeArticlesRoute,
  TenantApiKnowledgePlaybooksRoute: TenantApiKnowledgePlaybooksRoute,
  TenantApiKnowledgeSearchRoute: TenantApiKnowledgeSearchRoute,
  TenantApiProductCatalogAddOnsRoute: TenantApiProductCatalogAddOnsRoute,
  TenantApiProductCatalogPlansRoute:
    TenantApiProductCatalogPlansRouteWithChildren,
  TenantApiProductCatalogProductsRoute: TenantApiProductCatalogProductsRoute,
  TenantApiSettingsApiKeysRoute: TenantApiSettingsApiKeysRoute,
  TenantApiSupportOrganizationsOrganizationIdRoute:
    TenantApiSupportOrganizationsOrganizationIdRoute,
}

const TenantRouteWithChildren =
  TenantRoute._addFileChildren(TenantRouteChildren)

interface FormsRouteChildren {
  FormsAddressRoute: typeof FormsAddressRoute
  FormsSimpleRoute: typeof FormsSimpleRoute
}

const FormsRouteChildren: FormsRouteChildren = {
  FormsAddressRoute: FormsAddressRoute,
  FormsSimpleRoute: FormsSimpleRoute,
}

const FormsRouteWithChildren = FormsRoute._addFileChildren(FormsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TenantRoute: TenantRouteWithChildren,
  DatabaseRoute: DatabaseRoute,
  FormsRoute: FormsRouteWithChildren,
  McpRoute: McpRoute,
  StoreRoute: StoreRoute,
  TableRoute: TableRoute,
  TodosRoute: TodosRoute,
  ApiTodosRoute: ApiTodosRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiUserOrganizationsRoute: ApiUserOrganizationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
